/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV30BrandKnowledgeQaGetGetRequestExample struct {
	UserQuery      string                             `json:"user_query"`
	AccountId      int64                              `json:"account_id,omitempty"`
	BusinessType   BrandKnowledgeQaGetV30BusinessType `json:"business_type,omitempty"`
	SessionId      string                             `json:"session_id,omitempty"`
	ChatHistoryStr string                             `json:"chat_history_str,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v3.0/brand/knowledge_qa/get/ Get
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV30BrandKnowledgeQaGetGetRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.BrandKnowledgeQaGetV30Api().
		Get(ctx).
		AccessToken(accessToken).
		UserQuery(request.UserQuery).AccountId(request.AccountId).BusinessType(request.BusinessType).SessionId(request.SessionId).ChatHistoryStr(request.ChatHistoryStr).
		Execute()
	fmt.Println(ToJsonString(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
