/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV30CgTransferV2WalletCanTransferBalanceBetweenAccountGetGetRequestExample struct {
	AccountId               int64                                                                                   `json:"account_id"`
	Origin                  CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin                          `json:"origin"`
	UserType                CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30UserType                        `json:"user_type"`
	TransferParticipantList []*CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner `json:"transfer_participant_list"`
}

// url: https://api.oceanengine.com/open_api/v3.0/cg_transfer/v2/wallet/can_transfer_balance_between_account/get/ Get
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV30CgTransferV2WalletCanTransferBalanceBetweenAccountGetGetRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Api().
		Get(ctx).
		AccessToken(accessToken).
		AccountId(request.AccountId).Origin(request.Origin).UserType(request.UserType).TransferParticipantList(request.TransferParticipantList).
		Execute()
	fmt.Println(ToJsonString(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
