/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequestExample struct {
	CgTransferV2WalletTransferCreateV30Request CgTransferV2WalletTransferCreateV30Request `json:"CgTransferV2WalletTransferCreateV30Request,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v3.0/cg_transfer/v2/wallet/transfer/create/ Post
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.CgTransferV2WalletTransferCreateV30Api().
		Post(ctx).
		AccessToken(accessToken).
		CgTransferV2WalletTransferCreateV30Request(request.CgTransferV2WalletTransferCreateV30Request).
		Execute()
	fmt.Println(ToJsonString(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
