/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV30EbpTaskInfoGetGetRequestExample struct {
	EnterpriseOrganizationId int64                   `json:"enterprise_organization_id"`
	TaskId                   int64                   `json:"task_id"`
	Filter                   EbpTaskInfoGetV30Filter `json:"filter,omitempty"`
	Page                     int64                   `json:"page,omitempty"`
	PageSize                 int64                   `json:"page_size,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v3.0/ebp/task_info/get/ Get
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV30EbpTaskInfoGetGetRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.EbpTaskInfoGetV30Api().
		Get(ctx).
		AccessToken(accessToken).
		EnterpriseOrganizationId(request.EnterpriseOrganizationId).TaskId(request.TaskId).Filter(request.Filter).Page(request.Page).PageSize(request.PageSize).
		Execute()
	fmt.Println(ToJsonString(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
