/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV10QianchuanEntityCenterCreatePostRequestExample struct {
	Authorization                         string                                `json:"authorization,omitempty"`
	Caller                                string                                `json:"caller,omitempty"`
	QianchuanEntityCenterCreateV10Request QianchuanEntityCenterCreateV10Request `json:"QianchuanEntityCenterCreateV10Request,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v1.0/qianchuan_entity_center/create/ Post
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV10QianchuanEntityCenterCreatePostRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.QianchuanEntityCenterCreateV10Api().
		Post(ctx).
		AccessToken(accessToken).
		Authorization(request.Authorization).Caller(request.Caller).QianchuanEntityCenterCreateV10Request(request.QianchuanEntityCenterCreateV10Request).
		Execute()
	fmt.Println(string(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
