/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"

	ad_open_sdk_go "github.com/oceanengine/ad_open_sdk_go"
	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

type ApiOpenApiV10QianchuanEntityCenterGetGetRequestExample struct {
	AdvertiserId  int64  `json:"advertiser_id"`
	StartTime     string `json:"start_time"`
	EndTime       string `json:"end_time"`
	Authorization string `json:"authorization,omitempty"`
	Caller        string `json:"caller,omitempty"`
	Limit         int64  `json:"limit,omitempty"`
	Offset        int64  `json:"offset,omitempty"`
}

// url: https://api.oceanengine.com/open_api/v1.0/qianchuan_entity_center/get/ Get
func main() {
	const demoreq = ``
	const accessToken = "ACCESS_TOKEN"
	ctx := context.Background()

	configuration := config.NewConfiguration()
	apiClient := ad_open_sdk_go.Init(configuration)
	apiClient.SetLogEnable(true)

	var request ApiOpenApiV10QianchuanEntityCenterGetGetRequestExample
	err := json.Unmarshal([]byte(demoreq), &request)
	if err != nil {
		log.Fatal(err)
	}

	resp, httpRes, err := apiClient.QianchuanEntityCenterGetV10Api().
		Get(ctx).
		AccessToken(accessToken).
		AdvertiserId(request.AdvertiserId).StartTime(request.StartTime).EndTime(request.EndTime).Authorization(request.Authorization).Caller(request.Caller).Limit(request.Limit).Offset(request.Offset).
		Execute()
	fmt.Println(string(resp))
	resBytes, _ := io.ReadAll(httpRes.Body)
	fmt.Println(string(resBytes))
	fmt.Println(err)

}
