/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// CgTransferV2WalletTransferCreateV30ApiService CgTransferV2WalletTransferCreateV30Api service
type CgTransferV2WalletTransferCreateV30ApiService service

type ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest struct {
	ctx                                        context.Context
	ApiService                                 *CgTransferV2WalletTransferCreateV30ApiService
	cgTransferV2WalletTransferCreateV30Request *CgTransferV2WalletTransferCreateV30Request
}

func (r *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest) CgTransferV2WalletTransferCreateV30Request(cgTransferV2WalletTransferCreateV30Request CgTransferV2WalletTransferCreateV30Request) *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest {
	r.cgTransferV2WalletTransferCreateV30Request = &cgTransferV2WalletTransferCreateV30Request
	return r
}

func (r *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest) Execute() (*CgTransferV2WalletTransferCreateV30Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest) AccessToken(accessToken string) *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest) WithLog(enable bool) *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CgTransferV2WalletTransferCreatePost Method for OpenApiV30CgTransferV2WalletTransferCreatePost

发起转账，支持钱包<->钱包之间m:n转账，但一次转账一个钱包id不能既是减款方，也是加款方

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest
*/
func (a *CgTransferV2WalletTransferCreateV30ApiService) Post(ctx context.Context) *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest {
	return &ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CgTransferV2WalletTransferCreateV30Response
func (a *CgTransferV2WalletTransferCreateV30ApiService) postExecute(r *ApiOpenApiV30CgTransferV2WalletTransferCreatePostRequest) (*CgTransferV2WalletTransferCreateV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *CgTransferV2WalletTransferCreateV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/cg_transfer/v2/wallet/transfer/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.cgTransferV2WalletTransferCreateV30Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
