/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// ToolsProjectDiagnosisSuggestionListV30ApiService ToolsProjectDiagnosisSuggestionListV30Api service
type ToolsProjectDiagnosisSuggestionListV30ApiService service

type ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest struct {
	ctx          context.Context
	ApiService   *ToolsProjectDiagnosisSuggestionListV30ApiService
	projectIds   *[]int64
	advertiserId *int64
}

// 项目ID列表，最多100个
func (r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) ProjectIds(projectIds []int64) *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest {
	r.projectIds = &projectIds
	return r
}

// 广告主ID
func (r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest {
	r.advertiserId = &advertiserId
	return r
}

func (r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) Execute() (*ToolsProjectDiagnosisSuggestionListV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) AccessToken(accessToken string) *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) WithLog(enable bool) *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30ToolsProjectDiagnosisSuggestionListGet Method for OpenApiV30ToolsProjectDiagnosisSuggestionListGet

获取项目诊断建议

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest
*/
func (a *ToolsProjectDiagnosisSuggestionListV30ApiService) Get(ctx context.Context) *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest {
	return &ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ToolsProjectDiagnosisSuggestionListV30Response
func (a *ToolsProjectDiagnosisSuggestionListV30ApiService) getExecute(r *ApiOpenApiV30ToolsProjectDiagnosisSuggestionListGetRequest) (*ToolsProjectDiagnosisSuggestionListV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *ToolsProjectDiagnosisSuggestionListV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/tools/project_diagnosis/suggestion/list/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.projectIds == nil {
		return localVarReturnValue, nil, ReportError("projectIds is required and must be specified")
	}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "project_ids", r.projectIds)
	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
