/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// EbpGroupBindAccountDeleteV30ApiService EbpGroupBindAccountDeleteV30Api service
type EbpGroupBindAccountDeleteV30ApiService service

type ApiOpenApiV30EbpGroupBindAccountDeletePostRequest struct {
	ctx                                 context.Context
	ApiService                          *EbpGroupBindAccountDeleteV30ApiService
	ebpGroupBindAccountDeleteV30Request *EbpGroupBindAccountDeleteV30Request
}

func (r *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest) EbpGroupBindAccountDeleteV30Request(ebpGroupBindAccountDeleteV30Request EbpGroupBindAccountDeleteV30Request) *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest {
	r.ebpGroupBindAccountDeleteV30Request = &ebpGroupBindAccountDeleteV30Request
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest) Execute() (*EbpGroupBindAccountDeleteV30Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest) AccessToken(accessToken string) *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest) WithLog(enable bool) *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30EbpGroupBindAccountDeletePost Method for OpenApiV30EbpGroupBindAccountDeletePost

解绑组织绑定的账户

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30EbpGroupBindAccountDeletePostRequest
*/
func (a *EbpGroupBindAccountDeleteV30ApiService) Post(ctx context.Context) *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest {
	return &ApiOpenApiV30EbpGroupBindAccountDeletePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EbpGroupBindAccountDeleteV30Response
func (a *EbpGroupBindAccountDeleteV30ApiService) postExecute(r *ApiOpenApiV30EbpGroupBindAccountDeletePostRequest) (*EbpGroupBindAccountDeleteV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *EbpGroupBindAccountDeleteV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/ebp/group_bind_account/delete/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.ebpGroupBindAccountDeleteV30Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
