/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ApiService CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Api service
type CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ApiService service

type ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest struct {
	ctx                     context.Context
	ApiService              *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ApiService
	organizationId          *int64
	origin                  *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Origin
	userType                *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType
	transferParticipantList *[]*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner
}

// 组织id
func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) OrganizationId(organizationId int64) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	r.organizationId = &organizationId
	return r
}

// 转账来源
func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) Origin(origin CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Origin) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	r.origin = &origin
	return r
}

// 登录用户类型
func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) UserType(userType CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	r.userType = &userType
	return r
}

// 转账参与方列表，最多支持100个
func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) TransferParticipantList(transferParticipantList []*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	r.transferParticipantList = &transferParticipantList
	return r
}

func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) Execute() (*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) WithLog(enable bool) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGet Method for OpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGet

查询转出方与转入方之间最大可转金额，支持查询M:N。只支持钱包<->钱包场景

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest
*/
func (a *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest {
	return &ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Response
func (a *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ApiService) getExecute(r *ApiOpenApiV30CgTransferV3WalletCanTransferBalanceBetweenAccountGetGetRequest) (*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/cg_transfer/v3/wallet/can_transfer_balance_between_account/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.organizationId == nil {
		return localVarReturnValue, nil, ReportError("organizationId is required and must be specified")
	}
	if r.origin == nil {
		return localVarReturnValue, nil, ReportError("origin is required and must be specified")
	}
	if r.userType == nil {
		return localVarReturnValue, nil, ReportError("userType is required and must be specified")
	}
	if r.transferParticipantList == nil {
		return localVarReturnValue, nil, ReportError("transferParticipantList is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "organization_id", r.organizationId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "origin", r.origin)
	parameterAddToHeaderOrQuery(localVarQueryParams, "user_type", r.userType)
	parameterAddToHeaderOrQuery(localVarQueryParams, "transfer_participant_list", r.transferParticipantList)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
