/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// QianchuanEntityIdGetV10ApiService QianchuanEntityIdGetV10Api service
type QianchuanEntityIdGetV10ApiService service

type ApiOpenApiV10QianchuanEntityIdGetGetRequest struct {
	ctx          context.Context
	ApiService   *QianchuanEntityIdGetV10ApiService
	advertiserId *int64
	query        *string
}

// 查询广告主账户ID
func (r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV10QianchuanEntityIdGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

// 用户自然语言查询问题
func (r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) Query(query string) *ApiOpenApiV10QianchuanEntityIdGetGetRequest {
	r.query = &query
	return r
}

func (r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) Execute() ([]byte, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV10QianchuanEntityIdGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) WithLog(enable bool) *ApiOpenApiV10QianchuanEntityIdGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV10QianchuanEntityIdGetGet Method for OpenApiV10QianchuanEntityIdGetGet

将确定对象及条件快速转换为实体 ID 集合，供后续意图继续使用。

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV10QianchuanEntityIdGetGetRequest
*/
func (a *QianchuanEntityIdGetV10ApiService) Get(ctx context.Context) *ApiOpenApiV10QianchuanEntityIdGetGetRequest {
	return &ApiOpenApiV10QianchuanEntityIdGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return QianchuanEntityIdGetV10Response
func (a *QianchuanEntityIdGetV10ApiService) getExecute(r *ApiOpenApiV10QianchuanEntityIdGetGetRequest) ([]byte, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue []byte
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v1.0/qianchuan_entity_id/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.query == nil {
		return localVarReturnValue, nil, ReportError("query is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "query", r.query)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
