/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// EbpGroupBindAccountUpdateV30ApiService EbpGroupBindAccountUpdateV30Api service
type EbpGroupBindAccountUpdateV30ApiService service

type ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest struct {
	ctx                                 context.Context
	ApiService                          *EbpGroupBindAccountUpdateV30ApiService
	ebpGroupBindAccountUpdateV30Request *EbpGroupBindAccountUpdateV30Request
}

func (r *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest) EbpGroupBindAccountUpdateV30Request(ebpGroupBindAccountUpdateV30Request EbpGroupBindAccountUpdateV30Request) *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest {
	r.ebpGroupBindAccountUpdateV30Request = &ebpGroupBindAccountUpdateV30Request
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest) Execute() (*EbpGroupBindAccountUpdateV30Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest) AccessToken(accessToken string) *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest) WithLog(enable bool) *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30EbpGroupBindAccountUpdatePost Method for OpenApiV30EbpGroupBindAccountUpdatePost

工作台组织内账户转移

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest
*/
func (a *EbpGroupBindAccountUpdateV30ApiService) Post(ctx context.Context) *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest {
	return &ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EbpGroupBindAccountUpdateV30Response
func (a *EbpGroupBindAccountUpdateV30ApiService) postExecute(r *ApiOpenApiV30EbpGroupBindAccountUpdatePostRequest) (*EbpGroupBindAccountUpdateV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *EbpGroupBindAccountUpdateV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/ebp/group_bind_account/update/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.ebpGroupBindAccountUpdateV30Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
