/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// EbpGroupBindAccountCreateV30ApiService EbpGroupBindAccountCreateV30Api service
type EbpGroupBindAccountCreateV30ApiService service

type ApiOpenApiV30EbpGroupBindAccountCreatePostRequest struct {
	ctx                                 context.Context
	ApiService                          *EbpGroupBindAccountCreateV30ApiService
	ebpGroupBindAccountCreateV30Request *EbpGroupBindAccountCreateV30Request
}

func (r *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest) EbpGroupBindAccountCreateV30Request(ebpGroupBindAccountCreateV30Request EbpGroupBindAccountCreateV30Request) *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest {
	r.ebpGroupBindAccountCreateV30Request = &ebpGroupBindAccountCreateV30Request
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest) Execute() (*EbpGroupBindAccountCreateV30Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest) AccessToken(accessToken string) *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest) WithLog(enable bool) *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30EbpGroupBindAccountCreatePost Method for OpenApiV30EbpGroupBindAccountCreatePost

工作台组织绑定账户，支持通过主体、客户ID方式绑定

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30EbpGroupBindAccountCreatePostRequest
*/
func (a *EbpGroupBindAccountCreateV30ApiService) Post(ctx context.Context) *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest {
	return &ApiOpenApiV30EbpGroupBindAccountCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EbpGroupBindAccountCreateV30Response
func (a *EbpGroupBindAccountCreateV30ApiService) postExecute(r *ApiOpenApiV30EbpGroupBindAccountCreatePostRequest) (*EbpGroupBindAccountCreateV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *EbpGroupBindAccountCreateV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/ebp/group_bind_account/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.ebpGroupBindAccountCreateV30Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
