/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// QianchuanEntityCenterCreateV10ApiService QianchuanEntityCenterCreateV10Api service
type QianchuanEntityCenterCreateV10ApiService service

type ApiOpenApiV10QianchuanEntityCenterCreatePostRequest struct {
	ctx                                   context.Context
	ApiService                            *QianchuanEntityCenterCreateV10ApiService
	authorization                         *string
	caller                                *string
	qianchuanEntityCenterCreateV10Request *QianchuanEntityCenterCreateV10Request
}

// Entity Center 访问 Authorization，由接口固定注入
func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) Authorization(authorization string) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	r.authorization = &authorization
	return r
}

// Entity Center 调用方标识，由接口固定注入
func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) Caller(caller string) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	r.caller = &caller
	return r
}

func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) QianchuanEntityCenterCreateV10Request(qianchuanEntityCenterCreateV10Request QianchuanEntityCenterCreateV10Request) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	r.qianchuanEntityCenterCreateV10Request = &qianchuanEntityCenterCreateV10Request
	return r
}

func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) Execute() ([]byte, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) AccessToken(accessToken string) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) WithLog(enable bool) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV10QianchuanEntityCenterCreatePost Method for OpenApiV10QianchuanEntityCenterCreatePost

查询千川广告主 2026 ROI2 核心指标数据

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV10QianchuanEntityCenterCreatePostRequest
*/
func (a *QianchuanEntityCenterCreateV10ApiService) Post(ctx context.Context) *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest {
	return &ApiOpenApiV10QianchuanEntityCenterCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return QianchuanEntityCenterCreateV10Response
func (a *QianchuanEntityCenterCreateV10ApiService) postExecute(r *ApiOpenApiV10QianchuanEntityCenterCreatePostRequest) ([]byte, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue []byte
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v1.0/qianchuan_entity_center/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization)
	}
	if r.caller != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "caller", r.caller)
	}
	// body params
	localVarPostBody = r.qianchuanEntityCenterCreateV10Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
