/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// PromotionEcosystemRiskFailedReasonGetV30ApiService PromotionEcosystemRiskFailedReasonGetV30Api service
type PromotionEcosystemRiskFailedReasonGetV30ApiService service

type ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest struct {
	ctx          context.Context
	ApiService   *PromotionEcosystemRiskFailedReasonGetV30ApiService
	advertiserId *int64
	promotionId  *int64
}

func (r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

func (r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) PromotionId(promotionId int64) *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest {
	r.promotionId = &promotionId
	return r
}

func (r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) Execute() (*models.PromotionEcosystemRiskFailedReasonGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) WithLog(enable bool) *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30PromotionEcosystemRiskFailedReasonGetGet Method for OpenApiV30PromotionEcosystemRiskFailedReasonGetGet

获取单元下素材生态风险判定建议

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest
*/
func (a *PromotionEcosystemRiskFailedReasonGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest {
	return &ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return PromotionEcosystemRiskFailedReasonGetV30Response
func (a *PromotionEcosystemRiskFailedReasonGetV30ApiService) getExecute(r *ApiOpenApiV30PromotionEcosystemRiskFailedReasonGetGetRequest) (*models.PromotionEcosystemRiskFailedReasonGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.PromotionEcosystemRiskFailedReasonGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/promotion/ecosystem_risk_failed_reason/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.promotionId == nil {
		return localVarReturnValue, nil, ReportError("promotionId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "promotion_id", r.promotionId)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
