/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// UbaToolMidAdListV10ApiService UbaToolMidAdListV10Api service
type UbaToolMidAdListV10ApiService service

type ApiOpenApiV10UbaToolMidAdListGetRequest struct {
	ctx          context.Context
	ApiService   *UbaToolMidAdListV10ApiService
	cdpProjectId *int64
	legoMidList  *[]int64
	advertiserId *int64
	reason       *string
}

// 项目id
func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) CdpProjectId(cdpProjectId int64) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	r.cdpProjectId = &cdpProjectId
	return r
}

// 查询的project下对应的lego_mid的计划
func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) LegoMidList(legoMidList []int64) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	r.legoMidList = &legoMidList
	return r
}

// 广告主id
func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	r.advertiserId = &advertiserId
	return r
}

func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) Reason(reason string) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	r.reason = &reason
	return r
}

func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) Execute() (*models.UbaToolMidAdListV10Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) AccessToken(accessToken string) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV10UbaToolMidAdListGetRequest) WithLog(enable bool) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV10UbaToolMidAdListGet Method for OpenApiV10UbaToolMidAdListGet

项目下素材计划查询

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV10UbaToolMidAdListGetRequest
*/
func (a *UbaToolMidAdListV10ApiService) Get(ctx context.Context) *ApiOpenApiV10UbaToolMidAdListGetRequest {
	return &ApiOpenApiV10UbaToolMidAdListGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return UbaToolMidAdListV10Response
func (a *UbaToolMidAdListV10ApiService) getExecute(r *ApiOpenApiV10UbaToolMidAdListGetRequest) (*models.UbaToolMidAdListV10Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.UbaToolMidAdListV10Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v1.0/uba_tool/mid_ad/list/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.cdpProjectId == nil {
		return localVarReturnValue, nil, ReportError("cdpProjectId is required and must be specified")
	}
	if r.legoMidList == nil {
		return localVarReturnValue, nil, ReportError("legoMidList is required and must be specified")
	}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "cdp_project_id", r.cdpProjectId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "lego_mid_list", r.legoMidList)
	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	if r.reason != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "reason", r.reason)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
