/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// CgTransferV2BpTransferCreateV30ApiService CgTransferV2BpTransferCreateV30Api service
type CgTransferV2BpTransferCreateV30ApiService service

type ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest struct {
	ctx                                    context.Context
	ApiService                             *CgTransferV2BpTransferCreateV30ApiService
	cgTransferV2BpTransferCreateV30Request *CgTransferV2BpTransferCreateV30Request
}

func (r *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest) CgTransferV2BpTransferCreateV30Request(cgTransferV2BpTransferCreateV30Request CgTransferV2BpTransferCreateV30Request) *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest {
	r.cgTransferV2BpTransferCreateV30Request = &cgTransferV2BpTransferCreateV30Request
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest) Execute() (*CgTransferV2BpTransferCreateV30Response, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest) AccessToken(accessToken string) *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest) WithLog(enable bool) *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CgTransferV2BpTransferCreatePost Method for OpenApiV30CgTransferV2BpTransferCreatePost

发起转账，支持账户<->钱包、账户<->账户m:n转账，但一次转账一个账户id/钱包id不能既是减款方，也是加款方。
备款钱包与虚拟广告主不支持互转

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest
*/
func (a *CgTransferV2BpTransferCreateV30ApiService) Post(ctx context.Context) *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest {
	return &ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CgTransferV2BpTransferCreateV30Response
func (a *CgTransferV2BpTransferCreateV30ApiService) postExecute(r *ApiOpenApiV30CgTransferV2BpTransferCreatePostRequest) (*CgTransferV2BpTransferCreateV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *CgTransferV2BpTransferCreateV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/cg_transfer/v2/bp/transfer/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.cgTransferV2BpTransferCreateV30Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
