/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// CgTransferV2BpTransferDetailGetV30ApiService CgTransferV2BpTransferDetailGetV30Api service
type CgTransferV2BpTransferDetailGetV30ApiService service

type ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest struct {
	ctx                  context.Context
	ApiService           *CgTransferV2BpTransferDetailGetV30ApiService
	organizationId       *int64
	origin               *models.CgTransferV2BpTransferDetailGetV30Origin
	transferBizRequestNo *string
	transferSerial       *string
}

// 组织id
func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) OrganizationId(organizationId int64) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	r.organizationId = &organizationId
	return r
}

// 转账来源
func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) Origin(origin models.CgTransferV2BpTransferDetailGetV30Origin) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	r.origin = &origin
	return r
}

// 发起转账请求id（发起转账请求id、转账编号二选一传）
func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) TransferBizRequestNo(transferBizRequestNo string) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	r.transferBizRequestNo = &transferBizRequestNo
	return r
}

// 转账编号（发起转账请求id、转账编号二选一传）
func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) TransferSerial(transferSerial string) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	r.transferSerial = &transferSerial
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) Execute() (*models.CgTransferV2BpTransferDetailGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) WithLog(enable bool) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CgTransferV2BpTransferDetailGetGet Method for OpenApiV30CgTransferV2BpTransferDetailGetGet

查询单个转账单信息

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest
*/
func (a *CgTransferV2BpTransferDetailGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest {
	return &ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CgTransferV2BpTransferDetailGetV30Response
func (a *CgTransferV2BpTransferDetailGetV30ApiService) getExecute(r *ApiOpenApiV30CgTransferV2BpTransferDetailGetGetRequest) (*models.CgTransferV2BpTransferDetailGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.CgTransferV2BpTransferDetailGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/cg_transfer/v2/bp/transfer_detail/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.organizationId == nil {
		return localVarReturnValue, nil, ReportError("organizationId is required and must be specified")
	}
	if r.origin == nil {
		return localVarReturnValue, nil, ReportError("origin is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "organization_id", r.organizationId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "origin", r.origin)
	if r.transferBizRequestNo != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "transfer_biz_request_no", r.transferBizRequestNo)
	}
	if r.transferSerial != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "transfer_serial", r.transferSerial)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
