/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// OcProjectEcosystemRiskFailedReasonGetV30ApiService OcProjectEcosystemRiskFailedReasonGetV30Api service
type OcProjectEcosystemRiskFailedReasonGetV30ApiService service

type ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest struct {
	ctx          context.Context
	ApiService   *OcProjectEcosystemRiskFailedReasonGetV30ApiService
	advertiserId *int64
	projectId    *int64
	page         *int64
	pageSize     *int64
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) ProjectId(projectId int64) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	r.projectId = &projectId
	return r
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) Page(page int64) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	r.page = &page
	return r
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) PageSize(pageSize int64) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	r.pageSize = &pageSize
	return r
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) Execute() (*models.OcProjectEcosystemRiskFailedReasonGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) WithLog(enable bool) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30OcProjectEcosystemRiskFailedReasonGetGet Method for OpenApiV30OcProjectEcosystemRiskFailedReasonGetGet

获取投放项目下素材生态风险判定建议

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest
*/
func (a *OcProjectEcosystemRiskFailedReasonGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest {
	return &ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return OcProjectEcosystemRiskFailedReasonGetV30Response
func (a *OcProjectEcosystemRiskFailedReasonGetV30ApiService) getExecute(r *ApiOpenApiV30OcProjectEcosystemRiskFailedReasonGetGetRequest) (*models.OcProjectEcosystemRiskFailedReasonGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.OcProjectEcosystemRiskFailedReasonGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/oc_project/ecosystem_risk_failed_reason/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.projectId == nil {
		return localVarReturnValue, nil, ReportError("projectId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "project_id", r.projectId)
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page)
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize)
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
