/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// AdConvertAttributionQueryCreateV2ApiService AdConvertAttributionQueryCreateV2Api service
type AdConvertAttributionQueryCreateV2ApiService service

type ApiOpenApi2AdConvertAttributionQueryCreatePostRequest struct {
	ctx                                      context.Context
	ApiService                               *AdConvertAttributionQueryCreateV2ApiService
	adConvertAttributionQueryCreateV2Request *AdConvertAttributionQueryCreateV2Request
}

func (r *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest) AdConvertAttributionQueryCreateV2Request(adConvertAttributionQueryCreateV2Request AdConvertAttributionQueryCreateV2Request) *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest {
	r.adConvertAttributionQueryCreateV2Request = &adConvertAttributionQueryCreateV2Request
	return r
}

func (r *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest) Execute() ([]byte, *http.Response, error) {
	return r.ApiService.postExecute(r)
}

func (r *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest) AccessToken(accessToken string) *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest) WithLog(enable bool) *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApi2AdConvertAttributionQueryCreatePost Method for OpenApi2AdConvertAttributionQueryCreatePost

对实时归因接口进行鉴权

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApi2AdConvertAttributionQueryCreatePostRequest
*/
func (a *AdConvertAttributionQueryCreateV2ApiService) Post(ctx context.Context) *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest {
	return &ApiOpenApi2AdConvertAttributionQueryCreatePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AdConvertAttributionQueryCreateV2Response
func (a *AdConvertAttributionQueryCreateV2ApiService) postExecute(r *ApiOpenApi2AdConvertAttributionQueryCreatePostRequest) ([]byte, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue []byte
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/2/ad_convert/attribution_query/create/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// body params
	localVarPostBody = r.adConvertAttributionQueryCreateV2Request
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
