/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"

	"github.com/oceanengine/ad_open_sdk_go/models"
)

// EbpAdvBindGroupGetV30ApiService EbpAdvBindGroupGetV30Api service
type EbpAdvBindGroupGetV30ApiService service

type ApiOpenApiV30EbpAdvBindGroupGetGetRequest struct {
	ctx          context.Context
	ApiService   *EbpAdvBindGroupGetV30ApiService
	advertiserId *int64
	queryType    *models.EbpAdvBindGroupGetV30QueryType
}

func (r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) AdvertiserId(advertiserId int64) *ApiOpenApiV30EbpAdvBindGroupGetGetRequest {
	r.advertiserId = &advertiserId
	return r
}

// 查询组织层级方式
func (r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) QueryType(queryType models.EbpAdvBindGroupGetV30QueryType) *ApiOpenApiV30EbpAdvBindGroupGetGetRequest {
	r.queryType = &queryType
	return r
}

func (r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) Execute() (*models.EbpAdvBindGroupGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30EbpAdvBindGroupGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) WithLog(enable bool) *ApiOpenApiV30EbpAdvBindGroupGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30EbpAdvBindGroupGetGet Method for OpenApiV30EbpAdvBindGroupGetGet

查找账户绑定工作台组织

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30EbpAdvBindGroupGetGetRequest
*/
func (a *EbpAdvBindGroupGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30EbpAdvBindGroupGetGetRequest {
	return &ApiOpenApiV30EbpAdvBindGroupGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return EbpAdvBindGroupGetV30Response
func (a *EbpAdvBindGroupGetV30ApiService) getExecute(r *ApiOpenApiV30EbpAdvBindGroupGetGetRequest) (*models.EbpAdvBindGroupGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*models.FormFileInfo
		localVarReturnValue *models.EbpAdvBindGroupGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/ebp/adv_bind_group/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*models.FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.advertiserId == nil {
		return localVarReturnValue, nil, ReportError("advertiserId is required and must be specified")
	}
	if r.queryType == nil {
		return localVarReturnValue, nil, ReportError("queryType is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "advertiser_id", r.advertiserId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "query_type", r.queryType)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
