/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"net/url"

	"github.com/oceanengine/ad_open_sdk_go/config"
	. "github.com/oceanengine/ad_open_sdk_go/models"
)

// CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ApiService CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Api service
type CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ApiService service

type ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest struct {
	ctx                     context.Context
	ApiService              *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ApiService
	organizationId          *int64
	origin                  *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin
	transferParticipantList *[]*CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner
}

// 组织id
func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) OrganizationId(organizationId int64) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	r.organizationId = &organizationId
	return r
}

// 转账来源
func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) Origin(origin CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	r.origin = &origin
	return r
}

// 转账参与方列表，最多支持100个
func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) TransferParticipantList(transferParticipantList []*CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	r.transferParticipantList = &transferParticipantList
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) Execute() (*CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response, *http.Response, error) {
	return r.ApiService.getExecute(r)
}

func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) AccessToken(accessToken string) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	r.ctx = context.WithValue(r.ctx, config.ContextAccessToken, accessToken)
	return r
}

func (r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) WithLog(enable bool) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	if enable {
		r.ctx = context.WithValue(r.ctx, config.ContextEnableLog, true)
	}
	return r
}

/*
OpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGet Method for OpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGet

查询转出方与转入方之间最大可转金额，支持查询M:N。暂时只支持备款钱包<->投放账户场景

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest
*/
func (a *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ApiService) Get(ctx context.Context) *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest {
	return &ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response
func (a *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ApiService) getExecute(r *ApiOpenApiV30CgTransferV2BpCanTransferBalanceBetweenAccountGetGetRequest) (*CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           map[string]*FormFileInfo
		localVarReturnValue *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response
	)

	r.ctx = a.client.prepareCtx(r.ctx)

	localBasePath := a.client.Cfg.GetBasePath()

	localVarPath := localBasePath + "/open_api/v3.0/cg_transfer/v2/bp/can_transfer_balance_between_account/get/"

	localVarHeaderParams := make(map[string]string)
	formFiles = make(map[string]*FormFileInfo)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.organizationId == nil {
		return localVarReturnValue, nil, ReportError("organizationId is required and must be specified")
	}
	if r.origin == nil {
		return localVarReturnValue, nil, ReportError("origin is required and must be specified")
	}
	if r.transferParticipantList == nil {
		return localVarReturnValue, nil, ReportError("transferParticipantList is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "organization_id", r.organizationId)
	parameterAddToHeaderOrQuery(localVarQueryParams, "origin", r.origin)
	parameterAddToHeaderOrQuery(localVarQueryParams, "transfer_participant_list", r.transferParticipantList)
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.call(r.ctx, req, &localVarReturnValue)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
