/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner struct for CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner
type CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner struct {
	CapitalEnum    CgTransferV2WalletTransferCreateV30TransferParticipantListTransferCapitalListCapitalEnum     `json:"capital_enum"`
	CapitalSubType *CgTransferV2WalletTransferCreateV30TransferParticipantListTransferCapitalListCapitalSubType `json:"capital_sub_type,omitempty"`
	PayerPlatform  CgTransferV2WalletTransferCreateV30TransferParticipantListTransferCapitalListPayerPlatform   `json:"payer_platform"`
	// 转账金额 (单位:分)
	TransferAmount int64 `json:"transfer_amount"`
}
