/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30RequestAccountsInner struct for EbpGroupBindAccountDeleteV30RequestAccountsInner
type EbpGroupBindAccountDeleteV30RequestAccountsInner struct {
	// 通过指定账户ID解绑，上限1000个
	AccountIds  []int64                                         `json:"account_ids,omitempty"`
	AccountType EbpGroupBindAccountDeleteV30AccountsAccountType `json:"account_type"`
	// 通过全选组织下所有账户解绑
	GroupQueries []*EbpGroupBindAccountDeleteV30RequestAccountsInnerGroupQueriesInner `json:"group_queries,omitempty"`
}
