/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30DataAccountRowsSubTaskStatus
type EbpTaskInfoGetV30DataAccountRowsSubTaskStatus string

// List of ebp_task_info_get_v3.0_data_account_rows_sub_task_status
const (
	SUCCESS_EbpTaskInfoGetV30DataAccountRowsSubTaskStatus EbpTaskInfoGetV30DataAccountRowsSubTaskStatus = "SUCCESS"
	FAILED_EbpTaskInfoGetV30DataAccountRowsSubTaskStatus  EbpTaskInfoGetV30DataAccountRowsSubTaskStatus = "FAILED"
)

// Ptr returns reference to ebp_task_info_get_v3.0_data_account_rows_sub_task_status value
func (v EbpTaskInfoGetV30DataAccountRowsSubTaskStatus) Ptr() *EbpTaskInfoGetV30DataAccountRowsSubTaskStatus {
	return &v
}
