/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandKnowledgeQaGetV30ResponseData
type BrandKnowledgeQaGetV30ResponseData struct {
	// 回答
	Answer *string `json:"answer,omitempty"`
}
