/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// BrandKnowledgeQaGetV30BusinessType
type BrandKnowledgeQaGetV30BusinessType string

// List of brand_knowledge_qa_get_v3.0_business_type
const (
	AD_BrandKnowledgeQaGetV30BusinessType   BrandKnowledgeQaGetV30BusinessType = "AD"
	ECP_BrandKnowledgeQaGetV30BusinessType  BrandKnowledgeQaGetV30BusinessType = "ECP"
	SHOP_BrandKnowledgeQaGetV30BusinessType BrandKnowledgeQaGetV30BusinessType = "SHOP"
)

// Ptr returns reference to brand_knowledge_qa_get_v3.0_business_type value
func (v BrandKnowledgeQaGetV30BusinessType) Ptr() *BrandKnowledgeQaGetV30BusinessType {
	return &v
}
