/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30Filter
type EbpTaskInfoGetV30Filter struct {
	// 通过account_id过滤查询
	AccountId     *int64                                `json:"account_id,omitempty"`
	SubTaskStatus *EbpTaskInfoGetV30FilterSubTaskStatus `json:"sub_task_status,omitempty"`
}
