/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct for CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner
type CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct {
	Payee        CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayee   `json:"payee"`
	Payer        CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayer   `json:"payer"`
	TransferType CgTransferV2BpCanTransferBalanceBetweenAccountGetV30TransferParticipantListTransferType `json:"transfer_type"`
}
