/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpAdvBindGroupGetV30ResponseData
type EbpAdvBindGroupGetV30ResponseData struct {
	// 每个账户可能对应多个组织
	GroupInfos []*EbpAdvBindGroupGetV30ResponseDataGroupInfosInner `json:"group_infos"`
}
