/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferCreateV30Request struct for CgTransferV3WalletTransferCreateV30Request
type CgTransferV3WalletTransferCreateV30Request struct {
	// 幂等唯一转账请求ID
	BizRequestId string `json:"biz_request_id"`
	// 组织id
	OrganizationId int64                                     `json:"organization_id"`
	Origin         CgTransferV3WalletTransferCreateV30Origin `json:"origin"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 转账参与方列表，最多支持100个
	TransferParticipantList []*CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInner `json:"transfer_participant_list"`
	UserType                CgTransferV3WalletTransferCreateV30UserType                               `json:"user_type"`
}
