/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerCanTransferBalanceListInner struct for CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerCanTransferBalanceListInner
type CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerCanTransferBalanceListInner struct {
	CapitalEnum    *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30DataParticipantCanTransferBalanceListCanTransferBalanceListCapitalEnum    `json:"capital_enum,omitempty"`
	CapitalSource  *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30DataParticipantCanTransferBalanceListCanTransferBalanceListCapitalSource  `json:"capital_source,omitempty"`
	CapitalSubType *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30DataParticipantCanTransferBalanceListCanTransferBalanceListCapitalSubType `json:"capital_sub_type,omitempty"`
	//  减款方可转余额，单位分
	PayerCanTransferBalance *int64                                                                                                                   `json:"payer_can_transfer_balance,omitempty"`
	Platform                *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30DataParticipantCanTransferBalanceListCanTransferBalanceListPlatform `json:"platform,omitempty"`
}
