/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferDetailGetV30UserType
type CgTransferV2WalletTransferDetailGetV30UserType string

// List of cg_transfer_v2_wallet_transfer_detail_get_v3.0_user_type
const (
	AGENT_CgTransferV2WalletTransferDetailGetV30UserType CgTransferV2WalletTransferDetailGetV30UserType = "AGENT"
	BP_CgTransferV2WalletTransferDetailGetV30UserType    CgTransferV2WalletTransferDetailGetV30UserType = "BP"
)

// Ptr returns reference to cg_transfer_v2_wallet_transfer_detail_get_v3.0_user_type value
func (v CgTransferV2WalletTransferDetailGetV30UserType) Ptr() *CgTransferV2WalletTransferDetailGetV30UserType {
	return &v
}
