/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30RequestAccountsInner struct for EbpGroupBindAccountUpdateV30RequestAccountsInner
type EbpGroupBindAccountUpdateV30RequestAccountsInner struct {
	// 通过指定账户进行转移，上限1000个
	AccountIds  []int64                                         `json:"account_ids,omitempty"`
	AccountType EbpGroupBindAccountUpdateV30AccountsAccountType `json:"account_type"`
	// 通过全选团队下所有账户转移，上限5个
	GroupQueries []*EbpGroupBindAccountUpdateV30RequestAccountsInnerGroupQueriesInner `json:"group_queries,omitempty"`
}
