/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectListV30DataListAudienceCarrierRegionOptimize 运营商号段优化开关
type StdProjectListV30DataListAudienceCarrierRegionOptimize string

// List of std_project_list_v3.0_data_list_audience_carrier_region_optimize
const (
	OFF_StdProjectListV30DataListAudienceCarrierRegionOptimize StdProjectListV30DataListAudienceCarrierRegionOptimize = "OFF"
	ON_StdProjectListV30DataListAudienceCarrierRegionOptimize  StdProjectListV30DataListAudienceCarrierRegionOptimize = "ON"
)

// Ptr returns reference to std_project_list_v3.0_data_list_audience_carrier_region_optimize value
func (v StdProjectListV30DataListAudienceCarrierRegionOptimize) Ptr() *StdProjectListV30DataListAudienceCarrierRegionOptimize {
	return &v
}
