/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsExtremeMaterialLimitGetV30ResponseData
type ToolsExtremeMaterialLimitGetV30ResponseData struct {
	// 历史命中记录列表（含 WARN 与 LIMIT），受 start_date/end_date 参数控制。无命中或豁免主体均返回空数组。
	Records []*ToolsExtremeMaterialLimitGetV30ResponseDataRecordsInner `json:"records,omitempty"`
}
