/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30Request struct for EbpGroupBindAccountDeleteV30Request
type EbpGroupBindAccountDeleteV30Request struct {
	// 所选账户
	Accounts []*EbpGroupBindAccountDeleteV30RequestAccountsInner `json:"accounts"`
	// 操作的工作台组织
	EnterpriseOrganizationId int64 `json:"enterprise_organization_id"`
}
