/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolAdCreateCreateV10ResponseData
type UbaToolAdCreateCreateV10ResponseData struct {
	// 计划id
	AdIds []int64 `json:"ad_ids,omitempty"`
	// 额外附加信息
	Extra   *map[string]string                           `json:"extra,omitempty"`
	Preview *UbaToolAdCreateCreateV10ResponseDataPreview `json:"preview,omitempty"`
	// 操作的细节信息
	ResMsg *string `json:"res_msg,omitempty"`
	// 是否成功
	Success *bool `json:"success,omitempty"`
}
