/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// LocalImAutoSettingGetV30SourceName
type LocalImAutoSettingGetV30SourceName string

// List of local_im_auto_setting_get_v3.0_source_name
const (
	Enum_53_KF_LocalImAutoSettingGetV30SourceName      LocalImAutoSettingGetV30SourceName = "53KF"
	Enum_AI即用_LocalImAutoSettingGetV30SourceName       LocalImAutoSettingGetV30SourceName = "AI即用"
	Enum_云雀客服_LocalImAutoSettingGetV30SourceName       LocalImAutoSettingGetV30SourceName = "云雀客服"
	Enum_优居AI智慧客服系统_LocalImAutoSettingGetV30SourceName LocalImAutoSettingGetV30SourceName = "优居AI智慧客服系统"
	Enum_内部测试_LocalImAutoSettingGetV30SourceName       LocalImAutoSettingGetV30SourceName = "内部测试"
	Enum_北京易聊智能客服_LocalImAutoSettingGetV30SourceName   LocalImAutoSettingGetV30SourceName = "北京易聊智能客服"
	Enum_快商通在线客服_LocalImAutoSettingGetV30SourceName    LocalImAutoSettingGetV30SourceName = "快商通在线客服"
	Enum_智能云客_LocalImAutoSettingGetV30SourceName       LocalImAutoSettingGetV30SourceName = "智能云客"
	Enum_来鼓_LocalImAutoSettingGetV30SourceName         LocalImAutoSettingGetV30SourceName = "来鼓"
	Enum_杭州百聆科技有限公司_LocalImAutoSettingGetV30SourceName LocalImAutoSettingGetV30SourceName = "杭州百聆科技有限公司"
	Enum_百聆_LocalImAutoSettingGetV30SourceName         LocalImAutoSettingGetV30SourceName = "百聆"
	Enum_美洽客服_LocalImAutoSettingGetV30SourceName       LocalImAutoSettingGetV30SourceName = "美洽客服"
	Enum_螳螂CRM_LocalImAutoSettingGetV30SourceName      LocalImAutoSettingGetV30SourceName = "螳螂CRM"
)

// Ptr returns reference to local_im_auto_setting_get_v3.0_source_name value
func (v LocalImAutoSettingGetV30SourceName) Ptr() *LocalImAutoSettingGetV30SourceName {
	return &v
}
