/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectCreateV30AudienceCarrierRegionOptimize 运营商地域定向优化
type StdProjectCreateV30AudienceCarrierRegionOptimize string

// List of std_project_create_v3.0_audience_carrier_region_optimize
const (
	OFF_StdProjectCreateV30AudienceCarrierRegionOptimize StdProjectCreateV30AudienceCarrierRegionOptimize = "OFF"
	ON_StdProjectCreateV30AudienceCarrierRegionOptimize  StdProjectCreateV30AudienceCarrierRegionOptimize = "ON"
)

// Ptr returns reference to std_project_create_v3.0_audience_carrier_region_optimize value
func (v StdProjectCreateV30AudienceCarrierRegionOptimize) Ptr() *StdProjectCreateV30AudienceCarrierRegionOptimize {
	return &v
}
