/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferCreateV30Origin 转账来源
type CgTransferV3WalletTransferCreateV30Origin string

// List of cg_transfer_v3_wallet_transfer_create_v3.0_origin
const (
	AGENT_WALLET_MAPI_CgTransferV3WalletTransferCreateV30Origin CgTransferV3WalletTransferCreateV30Origin = "AGENT_WALLET_MAPI"
	BP_WALLET_MAPI_CgTransferV3WalletTransferCreateV30Origin    CgTransferV3WalletTransferCreateV30Origin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v3_wallet_transfer_create_v3.0_origin value
func (v CgTransferV3WalletTransferCreateV30Origin) Ptr() *CgTransferV3WalletTransferCreateV30Origin {
	return &v
}
