/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType
type PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType string

// List of promotion_ecosystem_risk_failed_reason_get_v3.0_data_material_reject_type
const (
	ANCHOR_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType                 PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "ANCHOR"
	AWEME_NICK_NAME_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType        PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "AWEME_NICK_NAME"
	CALL_TO_ACTION_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType         PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CALL_TO_ACTION"
	CREATIVE_CAROUSEL_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType      PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_CAROUSEL"
	CREATIVE_COMPONENT_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType     PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_COMPONENT"
	CREATIVE_IMAGE_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType         PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_IMAGE"
	CREATIVE_TITLE_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType         PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_TITLE"
	CREATIVE_URL_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType           PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_URL"
	CREATIVE_VIDEO_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType         PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_VIDEO"
	OPEN_URL_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType               PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "OPEN_URL"
	PRODUCT_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType                PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT"
	PRODUCT_DESCRIBE_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType       PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_DESCRIBE"
	PRODUCT_IMAGE_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType          PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_IMAGE"
	PRODUCT_SELLING_POINTS_PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_SELLING_POINTS"
)

// Ptr returns reference to promotion_ecosystem_risk_failed_reason_get_v3.0_data_material_reject_type value
func (v PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType) Ptr() *PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType {
	return &v
}
