/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30RequestTransferParticipantListInner struct for CgTransferV2BpTransferCreateV30RequestTransferParticipantListInner
type CgTransferV2BpTransferCreateV30RequestTransferParticipantListInner struct {
	Payee CgTransferV2BpTransferCreateV30RequestTransferParticipantListInnerPayee `json:"payee"`
	Payer CgTransferV2BpTransferCreateV30RequestTransferParticipantListInnerPayer `json:"payer"`
	// 转账参与方资金列表
	TransferCapitalList []*CgTransferV2BpTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner `json:"transfer_capital_list"`
	TransferType        CgTransferV2BpTransferCreateV30TransferParticipantListTransferType                            `json:"transfer_type"`
}
