/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType 全选组织下账户范围
type EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType string

// List of ebp_group_bind_account_update_v3.0_accounts_group_queries_query_type
const (
	DIRECT_EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType   EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType = "DIRECT"
	TRAVERSE_EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType = "TRAVERSE"
)

// Ptr returns reference to ebp_group_bind_account_update_v3.0_accounts_group_queries_query_type value
func (v EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType) Ptr() *EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType {
	return &v
}
