/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30ResponseDataAccountRowsInner struct for EbpTaskInfoGetV30ResponseDataAccountRowsInner
type EbpTaskInfoGetV30ResponseDataAccountRowsInner struct {
	//
	AccountId *int64 `json:"account_id,omitempty"`
	//
	FailMsg       *string                                        `json:"fail_msg,omitempty"`
	SubTaskStatus *EbpTaskInfoGetV30DataAccountRowsSubTaskStatus `json:"sub_task_status,omitempty"`
}
