/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectCreateV30AudienceCarrier
type StdProjectCreateV30AudienceCarrier string

// List of std_project_create_v3.0_audience_carrier
const (
	MOBILE_StdProjectCreateV30AudienceCarrier StdProjectCreateV30AudienceCarrier = "MOBILE"
	TELCOM_StdProjectCreateV30AudienceCarrier StdProjectCreateV30AudienceCarrier = "TELCOM"
	UNICOM_StdProjectCreateV30AudienceCarrier StdProjectCreateV30AudienceCarrier = "UNICOM"
)

// Ptr returns reference to std_project_create_v3.0_audience_carrier value
func (v StdProjectCreateV30AudienceCarrier) Ptr() *StdProjectCreateV30AudienceCarrier {
	return &v
}
