/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpAdvBindGroupGetV30QueryType
type EbpAdvBindGroupGetV30QueryType string

// List of ebp_adv_bind_group_get_v3.0_query_type
const (
	DIRECT_EbpAdvBindGroupGetV30QueryType EbpAdvBindGroupGetV30QueryType = "DIRECT"
	ROOT_EbpAdvBindGroupGetV30QueryType   EbpAdvBindGroupGetV30QueryType = "ROOT"
)

// Ptr returns reference to ebp_adv_bind_group_get_v3.0_query_type value
func (v EbpAdvBindGroupGetV30QueryType) Ptr() *EbpAdvBindGroupGetV30QueryType {
	return &v
}
