/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30UserType 登录用户类型
type CgTransferV2BpTransferCreateV30UserType string

// List of cg_transfer_v2_bp_transfer_create_v3.0_user_type
const (
	AGENT_CgTransferV2BpTransferCreateV30UserType CgTransferV2BpTransferCreateV30UserType = "AGENT"
	BP_CgTransferV2BpTransferCreateV30UserType    CgTransferV2BpTransferCreateV30UserType = "BP"
)

// Ptr returns reference to cg_transfer_v2_bp_transfer_create_v3.0_user_type value
func (v CgTransferV2BpTransferCreateV30UserType) Ptr() *CgTransferV2BpTransferCreateV30UserType {
	return &v
}
