/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferDetailGetV30Origin
type CgTransferV2WalletTransferDetailGetV30Origin string

// List of cg_transfer_v2_wallet_transfer_detail_get_v3.0_origin
const (
	AGENT_WALLET_MAPI_CgTransferV2WalletTransferDetailGetV30Origin CgTransferV2WalletTransferDetailGetV30Origin = "AGENT_WALLET_MAPI"
	BP_WALLET_MAPI_CgTransferV2WalletTransferDetailGetV30Origin    CgTransferV2WalletTransferDetailGetV30Origin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_wallet_transfer_detail_get_v3.0_origin value
func (v CgTransferV2WalletTransferDetailGetV30Origin) Ptr() *CgTransferV2WalletTransferDetailGetV30Origin {
	return &v
}
