/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInner struct for CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInner
type CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInner struct {
	Payee CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerPayee `json:"payee"`
	Payer CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerPayer `json:"payer"`
	// 转账参与方资金列表
	TransferCapitalList []*CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner `json:"transfer_capital_list"`
}
