/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectListV30DataListAudienceCarrier
type StdProjectListV30DataListAudienceCarrier string

// List of std_project_list_v3.0_data_list_audience_carrier
const (
	MOBILE_StdProjectListV30DataListAudienceCarrier StdProjectListV30DataListAudienceCarrier = "MOBILE"
	TELCOM_StdProjectListV30DataListAudienceCarrier StdProjectListV30DataListAudienceCarrier = "TELCOM"
	UNICOM_StdProjectListV30DataListAudienceCarrier StdProjectListV30DataListAudienceCarrier = "UNICOM"
)

// Ptr returns reference to std_project_list_v3.0_data_list_audience_carrier value
func (v StdProjectListV30DataListAudienceCarrier) Ptr() *StdProjectListV30DataListAudienceCarrier {
	return &v
}
