/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner struct for PromotionEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner
type PromotionEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner struct {
	//
	FailedDetail []string `json:"failed_detail,omitempty"`
	//
	Item *string `json:"item,omitempty"`
	//
	RejectReason []string                                                        `json:"reject_reason,omitempty"`
	Type         *PromotionEcosystemRiskFailedReasonGetV30DataMaterialRejectType `json:"type,omitempty"`
}
