/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30BindModelApplyBindType 绑定方式：当前支持主体方式绑定 or 客户关系方式绑定
type EbpGroupBindAccountCreateV30BindModelApplyBindType string

// List of ebp_group_bind_account_create_v3.0_bind_model_apply_bind_type
const (
	COMPANY_BIND_EbpGroupBindAccountCreateV30BindModelApplyBindType  EbpGroupBindAccountCreateV30BindModelApplyBindType = "COMPANY_BIND"
	CUSTOMER_BIND_EbpGroupBindAccountCreateV30BindModelApplyBindType EbpGroupBindAccountCreateV30BindModelApplyBindType = "CUSTOMER_BIND"
)

// Ptr returns reference to ebp_group_bind_account_create_v3.0_bind_model_apply_bind_type value
func (v EbpGroupBindAccountCreateV30BindModelApplyBindType) Ptr() *EbpGroupBindAccountCreateV30BindModelApplyBindType {
	return &v
}
