/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30TransferParticipantListTransferType 转账类型
type CgTransferV2BpTransferCreateV30TransferParticipantListTransferType string

// List of cg_transfer_v2_bp_transfer_create_v3.0_transfer_participant_list_transfer_type
const (
	ACCOUNT_WALLET_TRANSFER_CgTransferV2BpTransferCreateV30TransferParticipantListTransferType   CgTransferV2BpTransferCreateV30TransferParticipantListTransferType = "ACCOUNT_WALLET_TRANSFER"
	CRM_SELF_SERVICE_TRANSFER_CgTransferV2BpTransferCreateV30TransferParticipantListTransferType CgTransferV2BpTransferCreateV30TransferParticipantListTransferType = "CRM_SELF_SERVICE_TRANSFER"
	SVIP_TRANSFER_CgTransferV2BpTransferCreateV30TransferParticipantListTransferType             CgTransferV2BpTransferCreateV30TransferParticipantListTransferType = "SVIP_TRANSFER"
)

// Ptr returns reference to cg_transfer_v2_bp_transfer_create_v3.0_transfer_participant_list_transfer_type value
func (v CgTransferV2BpTransferCreateV30TransferParticipantListTransferType) Ptr() *CgTransferV2BpTransferCreateV30TransferParticipantListTransferType {
	return &v
}
