/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRange 备款钱包共享范围
type SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRange struct {
	// 共享范围的 list
	Items []*SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRangeItemsInner `json:"items,omitempty"`
}
