/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletSubWalletCreateV30Platform 平台标识位 ，在ebp for svip场景下需要传，其他场景不传
type SharedWalletSubWalletCreateV30Platform string

// List of shared_wallet_sub_wallet_create_v3.0_platform
const (
	SVIP_EBP_SharedWalletSubWalletCreateV30Platform SharedWalletSubWalletCreateV30Platform = "SVIP_EBP"
)

// Ptr returns reference to shared_wallet_sub_wallet_create_v3.0_platform value
func (v SharedWalletSubWalletCreateV30Platform) Ptr() *SharedWalletSubWalletCreateV30Platform {
	return &v
}
