/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QualAccountListV2ResponseData
type QualAccountListV2ResponseData struct {
	// 账户列表
	UserAccountInfos []*QualAccountListV2ResponseDataUserAccountInfosInner `json:"user_account_infos"`
}
