/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30Request struct for CgTransferV2BpTransferCreateV30Request
type CgTransferV2BpTransferCreateV30Request struct {
	// 幂等唯一转账请求ID
	BizRequestId string `json:"biz_request_id"`
	// 组织id
	OrganizationId int64                                 `json:"organization_id"`
	Origin         CgTransferV2BpTransferCreateV30Origin `json:"origin"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 转账参与方列表
	TransferParticipantList []*CgTransferV2BpTransferCreateV30RequestTransferParticipantListInner `json:"transfer_participant_list"`
	UserType                CgTransferV2BpTransferCreateV30UserType                               `json:"user_type"`
}
