/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// OcProjectEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner struct for OcProjectEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner
type OcProjectEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner struct {
	//
	FailedDetail []string `json:"failed_detail,omitempty"`
	//
	Item *string `json:"item,omitempty"`
	//
	RejectReason []string                                                        `json:"reject_reason,omitempty"`
	Type         *OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType `json:"type,omitempty"`
}
