/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsExtremeMaterialLimitGetV30DataRecordsDimension 命中层级：COMPANY company_id × 二级行业 / GROUP 关联组 × 二级行业
type ToolsExtremeMaterialLimitGetV30DataRecordsDimension string

// List of tools_extreme_material_limit_get_v3.0_data_records_dimension
const (
	COMPANY_ToolsExtremeMaterialLimitGetV30DataRecordsDimension ToolsExtremeMaterialLimitGetV30DataRecordsDimension = "COMPANY"
	GROUP_ToolsExtremeMaterialLimitGetV30DataRecordsDimension   ToolsExtremeMaterialLimitGetV30DataRecordsDimension = "GROUP"
)

// Ptr returns reference to tools_extreme_material_limit_get_v3.0_data_records_dimension value
func (v ToolsExtremeMaterialLimitGetV30DataRecordsDimension) Ptr() *ToolsExtremeMaterialLimitGetV30DataRecordsDimension {
	return &v
}
