/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType 通知类型：WARN / LIMIT
type ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType string

// List of tools_extreme_material_limit_get_v3.0_data_records_notification_type
const (
	LIMIT_ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType = "LIMIT"
	WARN_ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType  ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType = "WARN"
)

// Ptr returns reference to tools_extreme_material_limit_get_v3.0_data_records_notification_type value
func (v ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType) Ptr() *ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType {
	return &v
}
