/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType 钱包归属关系类型
type SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType string

// List of shared_wallet_wallet_info_get_v3.0_data_wallet_info_sub_wallet_info_ownership_type
const (
	AGENT_TO_AGENT_SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType = "AGENT_TO_AGENT"
	AGENT_TO_EBP_SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType   SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType = "AGENT_TO_EBP"
	EBP_SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType            SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType = "EBP"
)

// Ptr returns reference to shared_wallet_wallet_info_get_v3.0_data_wallet_info_sub_wallet_info_ownership_type value
func (v SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType) Ptr() *SharedWalletWalletInfoGetV30DataWalletInfoSubWalletInfoOwnershipType {
	return &v
}
