/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30ResponseData
type EbpTaskInfoGetV30ResponseData struct {
	// 任务详情，每个账户执行情况，只披露已完成账户的情况
	AccountRows []*EbpTaskInfoGetV30ResponseDataAccountRowsInner `json:"account_rows,omitempty"`
	// 任务失败数量
	FailCnt *int64 `json:"fail_cnt,omitempty"`
	// 任务成功数量
	SuccessCnt *int64 `json:"success_cnt,omitempty"`
	// 任务ID
	TaskId     *string                          `json:"task_id,omitempty"`
	TaskStatus *EbpTaskInfoGetV30DataTaskStatus `json:"task_status,omitempty"`
	// 任务总数
	TotalCnt *int64 `json:"total_cnt,omitempty"`
}
