/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolPredUpdateV10Request struct for UbaToolPredUpdateV10Request
type UbaToolPredUpdateV10Request struct {
	// 计划纠偏系数
	AdPvrCoef *map[string]float64 `json:"ad_pvr_coef,omitempty"`
	// 广告主ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 枚举类型1=IES，2=GIP，3=OTHER
	AppGroupName *int64 `json:"app_group_name,omitempty"`
	// cdp_project_id
	CdpProjectId *int64 `json:"cdp_project_id,omitempty"`
	// 投放的deep_bid_type
	DeepBidType *int64 `json:"deep_bid_type,omitempty"`
	// 投放的deep_external_action
	DeepExternalAction *int64 `json:"deep_external_action,omitempty"`
	// 预览模式，只返回预估结果不实际执行
	DryRun *bool `json:"dry_run,omitempty"`
	// 纠偏时间, 默认3天, 传极短时间等价于不纠偏
	DurationSeconds *int64 `json:"duration_seconds,omitempty"`
	// 投放external_action
	ExternalAction *int64 `json:"external_action,omitempty"`
	// 纠偏维度, 目前仅支持 AD=1 和 project=2, ADV=3目前不支持
	IdType int64 `json:"id_type"`
	// 纠偏系数
	PvrCoef *float64 `json:"pvr_coef,omitempty"`
	// 操作原因
	Reason *string `json:"reason,omitempty"`
}
