/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolMidAdListV10ResponseData
type UbaToolMidAdListV10ResponseData struct {
	// 额外附加信息
	Extra *map[string]string `json:"extra,omitempty"`
	// Mid对应的ad_id
	MidAdMap *map[string]int64                       `json:"mid_ad_map,omitempty"`
	Preview  *UbaToolMidAdListV10ResponseDataPreview `json:"preview,omitempty"`
	// 操作的细节信息
	ResMsg *string `json:"res_msg,omitempty"`
	// 是否成功
	Success *bool `json:"success,omitempty"`
}
