/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// OcProjectEcosystemRiskFailedReasonGetV30ResponseData
type OcProjectEcosystemRiskFailedReasonGetV30ResponseData struct {
	//
	MaterialReject []*OcProjectEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner `json:"material_reject,omitempty"`
	PageInfo       *OcProjectEcosystemRiskFailedReasonGetV30ResponseDataPageInfo              `json:"page_info,omitempty"`
	//
	ProjectId *int64 `json:"project_id,omitempty"`
}
