/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// FileRebateRebateDownloadCreateTaskV2PricingCategory 计费类型，枚举值：BRAND-品牌、BID-竞价
type FileRebateRebateDownloadCreateTaskV2PricingCategory string

// List of file_rebate_rebate_download_create_task_v2_pricing_category
const (
	BRAND_FileRebateRebateDownloadCreateTaskV2PricingCategory FileRebateRebateDownloadCreateTaskV2PricingCategory = "BRAND"
	BID_FileRebateRebateDownloadCreateTaskV2PricingCategory   FileRebateRebateDownloadCreateTaskV2PricingCategory = "BID"
)

// Ptr returns reference to file_rebate_rebate_download_create_task_v2_pricing_category value
func (v FileRebateRebateDownloadCreateTaskV2PricingCategory) Ptr() *FileRebateRebateDownloadCreateTaskV2PricingCategory {
	return &v
}
