/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsExtremeMaterialLimitGetV30NotificationType
type ToolsExtremeMaterialLimitGetV30NotificationType string

// List of tools_extreme_material_limit_get_v3.0_notification_type
const (
	LIMIT_ToolsExtremeMaterialLimitGetV30NotificationType ToolsExtremeMaterialLimitGetV30NotificationType = "LIMIT"
	WARN_ToolsExtremeMaterialLimitGetV30NotificationType  ToolsExtremeMaterialLimitGetV30NotificationType = "WARN"
)

// Ptr returns reference to tools_extreme_material_limit_get_v3.0_notification_type value
func (v ToolsExtremeMaterialLimitGetV30NotificationType) Ptr() *ToolsExtremeMaterialLimitGetV30NotificationType {
	return &v
}
