/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct for CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner
type CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct {
	Payee CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayee `json:"payee"`
	Payer CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayer `json:"payer"`
}
