/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolStopUpdateV10ResponseData
type UbaToolStopUpdateV10ResponseData struct {
	// 额外附加信息
	Extra *map[string]string `json:"extra,omitempty"`
	// 关停失败计划ids
	FailedIds []int64                                  `json:"failed_ids,omitempty"`
	Preview   *UbaToolStopUpdateV10ResponseDataPreview `json:"preview,omitempty"`
	// 操作的细节信息
	ResMsg *string `json:"res_msg,omitempty"`
	// 是否成功
	Success *bool `json:"success,omitempty"`
	// 关停成功计划ids
	SuccessIds []int64 `json:"success_ids,omitempty"`
}
