/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin
type CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin string

// List of cg_transfer_v2_bp_can_transfer_balance_between_account_get_v3.0_origin
const (
	BP_ACCOUNT_WALLET_MAPI_CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin = "BP_ACCOUNT_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_bp_can_transfer_balance_between_account_get_v3.0_origin value
func (v CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin) Ptr() *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Origin {
	return &v
}
