/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInner struct for CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInner
type CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInner struct {
	// 账户间可转金额列表
	CanTransferBalanceList []*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerCanTransferBalanceListInner `json:"can_transfer_balance_list,omitempty"`
	Payee                  CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerPayee                          `json:"payee"`
	// 加款方保证金总金额，单位分
	PayeeDepositAmount *int64 `json:"payee_deposit_amount,omitempty"`
	// 加款方非品牌最小转入金额，单位分
	PayeeMinNoBrandTransferIn *int64                                                                                                          `json:"payee_min_no_brand_transfer_in,omitempty"`
	Payer                     CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerPayer `json:"payer"`
	// 减款方余额列表
	PayerBalances []*CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerPayerBalancesInner `json:"payer_balances,omitempty"`
	// 减款方保证金总金额，单位分
	PayerDepositAmount *int64 `json:"payer_deposit_amount,omitempty"`
	// 减款方非品牌最大可转出金额，单位分
	PayerMaxNoBrandTransferOut *int64 `json:"payer_max_no_brand_transfer_out,omitempty"`
}
