/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerPayee 加款方
type CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInnerPayee struct {
	// 加款方账户id
	AccountId           *int64                                                                                                                 `json:"account_id,omitempty"`
	AccountTypeCategory *CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30DataParticipantCanTransferBalanceListPayeeAccountTypeCategory `json:"account_type_category,omitempty"`
}
