/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30ResponseData
type CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30ResponseData struct {
	// 参与方可转金额列表
	ParticipantCanTransferBalanceList []*CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30ResponseDataParticipantCanTransferBalanceListInner `json:"participant_can_transfer_balance_list,omitempty"`
}
