/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30ResponseData
type EbpGroupBindAccountUpdateV30ResponseData struct {
	//
	FailedAccounts []*EbpGroupBindAccountUpdateV30ResponseDataFailedAccountsInner `json:"failed_accounts,omitempty"`
	// 默认同步执行，超出xx账户数量，进任务中心
	IsAsync *bool `json:"is_async,omitempty"`
	//
	TaskId *int64 `json:"task_id,omitempty"`
}
