/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30AccountsAccountType 账户的业务线
type EbpGroupBindAccountUpdateV30AccountsAccountType string

// List of ebp_group_bind_account_update_v3.0_accounts_account_type
const (
	AD_EbpGroupBindAccountUpdateV30AccountsAccountType        EbpGroupBindAccountUpdateV30AccountsAccountType = "AD"
	DOU_PLUS_EbpGroupBindAccountUpdateV30AccountsAccountType  EbpGroupBindAccountUpdateV30AccountsAccountType = "DOU_PLUS"
	LOCAL_EbpGroupBindAccountUpdateV30AccountsAccountType     EbpGroupBindAccountUpdateV30AccountsAccountType = "LOCAL"
	QIANCHUAN_EbpGroupBindAccountUpdateV30AccountsAccountType EbpGroupBindAccountUpdateV30AccountsAccountType = "QIANCHUAN"
	STAR_EbpGroupBindAccountUpdateV30AccountsAccountType      EbpGroupBindAccountUpdateV30AccountsAccountType = "STAR"
)

// Ptr returns reference to ebp_group_bind_account_update_v3.0_accounts_account_type value
func (v EbpGroupBindAccountUpdateV30AccountsAccountType) Ptr() *EbpGroupBindAccountUpdateV30AccountsAccountType {
	return &v
}
