/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdConvertAttributionQueryCreateV2Request struct for AdConvertAttributionQueryCreateV2Request
type AdConvertAttributionQueryCreateV2Request struct {
	//
	AdvertiserId int64 `json:"advertiser_id"`
	// Android设备标识符。platform为android时，android_id与device_id至少传一个
	AndroidId *string `json:"android_id,omitempty"`
	// 客户侧激活时间，毫秒级时间戳；传入非0值时必须处于当前时间前后7天范围内
	CustomerActiveTime int64 `json:"customer_active_time"`
	// iOS用户设备标识符，platform为ios时必传
	Idfv *string `json:"idfv,omitempty"`
	// 鸿蒙设备标识符。platform为open_harmony时，odid与device_id至少传一个
	Odid *string `json:"odid,omitempty"`
	// 应用包名
	PackageName string `json:"package_name"`
	// 系统类型： iOS：ios 安卓：android 鸿蒙：open_harmony
	Platform string `json:"platform"`
}
