/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30RequestAccountsInnerGroupQueriesInner struct for EbpGroupBindAccountDeleteV30RequestAccountsInnerGroupQueriesInner
type EbpGroupBindAccountDeleteV30RequestAccountsInnerGroupQueriesInner struct {
	// 全选的组织ID
	GroupId   int64                                                     `json:"group_id"`
	QueryType EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType `json:"query_type"`
}
