/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30DataTaskStatus 任务状态/进度
type EbpTaskInfoGetV30DataTaskStatus string

// List of ebp_task_info_get_v3.0_data_task_status
const (
	DONE_EbpTaskInfoGetV30DataTaskStatus            EbpTaskInfoGetV30DataTaskStatus = "DONE"
	EXPIRED_EbpTaskInfoGetV30DataTaskStatus         EbpTaskInfoGetV30DataTaskStatus = "EXPIRED"
	FAILED_EbpTaskInfoGetV30DataTaskStatus          EbpTaskInfoGetV30DataTaskStatus = "FAILED"
	PARTIAL_SUCCESS_EbpTaskInfoGetV30DataTaskStatus EbpTaskInfoGetV30DataTaskStatus = "PARTIAL_SUCCESS"
	RUNNING_EbpTaskInfoGetV30DataTaskStatus         EbpTaskInfoGetV30DataTaskStatus = "RUNNING"
	UNKNOWN_EbpTaskInfoGetV30DataTaskStatus         EbpTaskInfoGetV30DataTaskStatus = "UNKNOWN"
)

// Ptr returns reference to ebp_task_info_get_v3.0_data_task_status value
func (v EbpTaskInfoGetV30DataTaskStatus) Ptr() *EbpTaskInfoGetV30DataTaskStatus {
	return &v
}
