/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AdvertiserCancelableGetV2ResponseData
type AdvertiserCancelableGetV2ResponseData struct {
	// 账户类型：1直客 2虚客
	AccountType *int64 `json:"account_type,omitempty"`
	// 虚客对应的服务商公司名称
	AgentCompanyName *string `json:"agent_company_name,omitempty"`
	// 话术8：不满足注销的原因列表
	CancelBlockReasons []string `json:"cancel_block_reasons,omitempty"`
	// 是否可注销
	Deletable bool `json:"deletable"`
}
