/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30RequestAccountsInner struct for EbpGroupBindAccountCreateV30RequestAccountsInner
type EbpGroupBindAccountCreateV30RequestAccountsInner struct {
	// 通过指定账户方式绑定，上限1000个。
	AccountIds  []int64                                         `json:"account_ids,omitempty"`
	AccountType EbpGroupBindAccountCreateV30AccountsAccountType `json:"account_type"`
	// 绑定主体ID下该业务线所有账户
	AllCompanyAccount *bool `json:"all_company_account,omitempty"`
	// 绑定客户ID下该业务线所有账户
	AllCustomerAccount *bool `json:"all_customer_account,omitempty"`
	// 是否只绑活跃账户，仅针对ad账户生效，只能传true或不传改值
	OnlyActive *bool `json:"only_active,omitempty"`
}
