/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsExtremeMaterialLimitGetV30ResponseDataRecordsInner struct for ToolsExtremeMaterialLimitGetV30ResponseDataRecordsInner
type ToolsExtremeMaterialLimitGetV30ResponseDataRecordsInner struct {
	Dimension *ToolsExtremeMaterialLimitGetV30DataRecordsDimension `json:"dimension,omitempty"`
	// 限制截止日期（LIMIT 时有值），格式 yyyy-mm-dd
	LimitEndDate *string `json:"limit_end_date,omitempty"`
	// 限制起始日期（LIMIT 时有值），格式 yyyy-mm-dd
	LimitStartDate   *string                                                     `json:"limit_start_date,omitempty"`
	NotificationType *ToolsExtremeMaterialLimitGetV30DataRecordsNotificationType `json:"notification_type,omitempty"`
	// 二级行业 ID
	SecondIndustryId *int64 `json:"second_industry_id,omitempty"`
	// 二级行业名称
	SecondIndustryName *string `json:"second_industry_name,omitempty"`
	// 命中日期，格式 yyyy-mm-dd
	TriggerDate *string `json:"trigger_date,omitempty"`
}
