/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferDetailGetV30ResponseData
type CgTransferV3WalletTransferDetailGetV30ResponseData struct {
	// 账户维度转账结果列表
	AccountTransferOrderResultList []*CgTransferV3WalletTransferDetailGetV30ResponseDataAccountTransferOrderResultListInner `json:"account_transfer_order_result_list,omitempty"`
	// 转账请求id
	BizRequestNo *string `json:"biz_request_no,omitempty"`
	// 操作人
	OperatorId *int64 `json:"operator_id,omitempty"`
	// operatorName
	OperatorName *string                                           `json:"operator_name,omitempty"`
	Origin       *CgTransferV3WalletTransferDetailGetV30DataOrigin `json:"origin,omitempty"`
	// 转账备注
	Remark *string `json:"remark,omitempty"`
	// 转账金额 (单位:分)
	TransferAmount *int64 `json:"transfer_amount,omitempty"`
	// 转账创建时间
	TransferCreateTime *string `json:"transfer_create_time,omitempty"`
	// 转账完成时间
	TransferFinishTime *string `json:"transfer_finish_time,omitempty"`
	// 转账编号
	TransferSerial *string                                                   `json:"transfer_serial,omitempty"`
	TransferStatus *CgTransferV3WalletTransferDetailGetV30DataTransferStatus `json:"transfer_status,omitempty"`
}
