/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInner struct for CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInner
type CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInner struct {
	Payee CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerPayee `json:"payee"`
	Payer CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerPayer `json:"payer"`
	// 转账参与方资金列表
	TransferCapitalList []*CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner `json:"transfer_capital_list"`
}
