/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolPredUpdateV10ResponseData
type UbaToolPredUpdateV10ResponseData struct {
	// 额外附加信息
	Extra   *map[string]string                       `json:"extra,omitempty"`
	Preview *UbaToolPredUpdateV10ResponseDataPreview `json:"preview,omitempty"`
	// 操作的细节信息
	ResMsg *string `json:"res_msg,omitempty"`
	// 是否成功
	Success *bool `json:"success,omitempty"`
}
