/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolStopUpdateV10Request struct for UbaToolStopUpdateV10Request
type UbaToolStopUpdateV10Request struct {
	// 指定关停的素材
	AdIds []int64 `json:"ad_ids,omitempty"`
	// 广告主ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 项目id
	CdpProjectId int64 `json:"cdp_project_id"`
	// 预览模式，只返回预估结果不实际执行
	DryRun *bool `json:"dry_run,omitempty"`
	// 操作原因
	Reason *string `json:"reason,omitempty"`
}
