/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct for CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner
type CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInner struct {
	Payee CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayee `json:"payee"`
	Payer CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayer `json:"payer"`
}
