/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30Request struct for EbpGroupBindAccountCreateV30Request
type EbpGroupBindAccountCreateV30Request struct {
	// 绑定的账户范围
	Accounts  []*EbpGroupBindAccountCreateV30RequestAccountsInner `json:"accounts"`
	BindModel EbpGroupBindAccountCreateV30RequestBindModel        `json:"bind_model"`
	// 绑定的目标组织
	EnterpriseOrganizationId int64 `json:"enterprise_organization_id"`
}
