/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolAdCreateCreateV10ResponseDataPreview dry_run 预估结果
type UbaToolAdCreateCreateV10ResponseDataPreview struct {
	// 受影响的广告数
	AffectedAdCount *int64 `json:"affected_ad_count,omitempty"`
	// 受影响的计划数
	AffectedCampaignCount *int64 `json:"affected_campaign_count,omitempty"`
	// 预估消耗变化（元/天）
	EstimatedCostChange *int64 `json:"estimated_cost_change,omitempty"`
	// 风险提示
	Warning *string `json:"warning,omitempty"`
	// 预估是否会成功
	WillSucceed *bool `json:"will_succeed,omitempty"`
}
