/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpSubGroupCreateV30ResponseData
type EbpSubGroupCreateV30ResponseData struct {
	// 创建成功则有groupId返回
	GroupId *int64 `json:"group_id,omitempty"`
}
