/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30ResponseData
type EbpGroupBindAccountCreateV30ResponseData struct {
	//
	FailedAccounts []*EbpGroupBindAccountCreateV30ResponseDataFailedAccountsInner `json:"failed_accounts,omitempty"`
	// 是否异步执行，超出一定账户数量，会异步执行。
	IsAsync *bool `json:"is_async,omitempty"`
	// 异步执行时，任务ID
	TaskId *int64 `json:"task_id,omitempty"`
}
