/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30RequestTransferParticipantListInnerPayee 加款方
type CgTransferV2BpTransferCreateV30RequestTransferParticipantListInnerPayee struct {
	// 加款方账户id
	AccountId   int64                                                                  `json:"account_id"`
	AccountType CgTransferV2BpTransferCreateV30TransferParticipantListPayeeAccountType `json:"account_type"`
}
