/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30Request struct for EbpGroupBindAccountUpdateV30Request
type EbpGroupBindAccountUpdateV30Request struct {
	// 所选账户，上限5个
	Accounts []*EbpGroupBindAccountUpdateV30RequestAccountsInner `json:"accounts"`
	//
	EnterpriseOrganizationId int64 `json:"enterprise_organization_id"`
	// 要转移到的目标组织节点
	ToGroupId int64 `json:"to_group_id"`
}
