/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner struct for CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner
type CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerTransferCapitalListInner struct {
	CapitalEnum    CgTransferV3WalletTransferCreateV30TransferParticipantListTransferCapitalListCapitalEnum     `json:"capital_enum"`
	CapitalSubType *CgTransferV3WalletTransferCreateV30TransferParticipantListTransferCapitalListCapitalSubType `json:"capital_sub_type,omitempty"`
	PayerPlatform  CgTransferV3WalletTransferCreateV30TransferParticipantListTransferCapitalListPayerPlatform   `json:"payer_platform"`
	// 转账金额 (单位:分)
	TransferAmount int64 `json:"transfer_amount"`
}
