/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferDetailGetV30Origin
type CgTransferV2BpTransferDetailGetV30Origin string

// List of cg_transfer_v2_bp_transfer_detail_get_v3.0_origin
const (
	BP_ACCOUNT_WALLET_MAPI_CgTransferV2BpTransferDetailGetV30Origin CgTransferV2BpTransferDetailGetV30Origin = "BP_ACCOUNT_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_bp_transfer_detail_get_v3.0_origin value
func (v CgTransferV2BpTransferDetailGetV30Origin) Ptr() *CgTransferV2BpTransferDetailGetV30Origin {
	return &v
}
