/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolRitUpdateV10Request struct for UbaToolRitUpdateV10Request
type UbaToolRitUpdateV10Request struct {
	// 广告主ID
	AdvertiserId int64 `json:"advertiser_id"`
	// campaign_id 可选
	CampaignId *int64 `json:"campaign_id,omitempty"`
	// cdp project_id 必填
	CdpProjectId int64 `json:"cdp_project_id"`
	// 预览模式，只返回预估结果不实际执行
	DryRun *bool `json:"dry_run,omitempty"`
	// 点位的屏蔽时间, 默认3天, 传极短时间等价于放开屏蔽
	DurationSeconds *int64 `json:"duration_seconds,omitempty"`
	// 操作原因
	Reason *string `json:"reason,omitempty"`
	// RIT 点位ID列表，
	RitIds []int64 `json:"rit_ids"`
}
