/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30Response struct for EbpGroupBindAccountCreateV30Response
type EbpGroupBindAccountCreateV30Response struct {
	//
	Code *int64                                    `json:"code,omitempty"`
	Data *EbpGroupBindAccountCreateV30ResponseData `json:"data,omitempty"`
	//
	Message *string `json:"message,omitempty"`
	//
	RequestId *string `json:"request_id,omitempty"`
}
