/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// NearRealtimeCostGetV30ResponseData
type NearRealtimeCostGetV30ResponseData struct {
	//
	List     []*NearRealtimeCostGetV30ResponseDataListInner `json:"list,omitempty"`
	PageInfo *NearRealtimeCostGetV30ResponseDataPageInfo    `json:"page_info,omitempty"`
}
