/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRangeItemsInner struct for SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRangeItemsInner
type SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRangeItemsInner struct {
	AccountPlatform  *SharedWalletWalletInfoGetV30DataWalletInfoManageWalletInfoMainSharedRangeItemsAccountPlatform  `json:"account_platform,omitempty"`
	CustomerCategory *SharedWalletWalletInfoGetV30DataWalletInfoManageWalletInfoMainSharedRangeItemsCustomerCategory `json:"customer_category,omitempty"`
}
