/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferCreateV30Request struct for CgTransferV2WalletTransferCreateV30Request
type CgTransferV2WalletTransferCreateV30Request struct {
	// 鉴权账户
	AccountId int64 `json:"account_id"`
	// 幂等唯一转账请求ID
	BizRequestId string                                    `json:"biz_request_id"`
	Origin       CgTransferV2WalletTransferCreateV30Origin `json:"origin"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 转账参与方列表，最多支持100个
	TransferParticipantList []*CgTransferV2WalletTransferCreateV30RequestTransferParticipantListInner `json:"transfer_participant_list"`
	UserType                CgTransferV2WalletTransferCreateV30UserType                               `json:"user_type"`
}
