/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpTaskInfoGetV30FilterSubTaskStatus 筛选任务中的处理状态
type EbpTaskInfoGetV30FilterSubTaskStatus string

// List of ebp_task_info_get_v3.0_filter_sub_task_status
const (
	SUCCESS_EbpTaskInfoGetV30FilterSubTaskStatus EbpTaskInfoGetV30FilterSubTaskStatus = "SUCCESS"
	FAILED_EbpTaskInfoGetV30FilterSubTaskStatus  EbpTaskInfoGetV30FilterSubTaskStatus = "FAILED"
)

// Ptr returns reference to ebp_task_info_get_v3.0_filter_sub_task_status value
func (v EbpTaskInfoGetV30FilterSubTaskStatus) Ptr() *EbpTaskInfoGetV30FilterSubTaskStatus {
	return &v
}
