/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30RequestBindModel 绑定方式
type EbpGroupBindAccountCreateV30RequestBindModel struct {
	ApplyBindType EbpGroupBindAccountCreateV30BindModelApplyBindType `json:"apply_bind_type"`
	// 主体id, 通用主体方式绑定时必传
	CompanyId *int64 `json:"company_id,omitempty"`
	// 客户id, 通过客账关系绑定时必传
	CustomerId *int64 `json:"customer_id,omitempty"`
}
