/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferDetailGetV30DataOrigin 转账来源
type CgTransferV2WalletTransferDetailGetV30DataOrigin string

// List of cg_transfer_v2_wallet_transfer_detail_get_v3.0_data_origin
const (
	AGENT_MAPI_CgTransferV2WalletTransferDetailGetV30DataOrigin             CgTransferV2WalletTransferDetailGetV30DataOrigin = "AGENT_MAPI"
	AGENT_WALLET_MAPI_CgTransferV2WalletTransferDetailGetV30DataOrigin      CgTransferV2WalletTransferDetailGetV30DataOrigin = "AGENT_WALLET_MAPI"
	BP_ACCOUNT_WALLET_MAPI_CgTransferV2WalletTransferDetailGetV30DataOrigin CgTransferV2WalletTransferDetailGetV30DataOrigin = "BP_ACCOUNT_WALLET_MAPI"
	BP_MAPI_CgTransferV2WalletTransferDetailGetV30DataOrigin                CgTransferV2WalletTransferDetailGetV30DataOrigin = "BP_MAPI"
	BP_WALLET_MAPI_CgTransferV2WalletTransferDetailGetV30DataOrigin         CgTransferV2WalletTransferDetailGetV30DataOrigin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_wallet_transfer_detail_get_v3.0_data_origin value
func (v CgTransferV2WalletTransferDetailGetV30DataOrigin) Ptr() *CgTransferV2WalletTransferDetailGetV30DataOrigin {
	return &v
}
