/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanEntityCenterCreateV10Request struct for QianchuanEntityCenterCreateV10Request
type QianchuanEntityCenterCreateV10Request struct {
	// 广告主 ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 查询结束时间，支持 yyyy-MM-dd HH:mm:ss 或 yyyyMMdd
	EndTime string `json:"end_time"`
	// 返回条数，默认 100
	Limit *int64 `json:"limit,omitempty"`
	// 分页偏移量，默认 0
	Offset *int64 `json:"offset,omitempty"`
	// 查询开始时间，支持 yyyy-MM-dd HH:mm:ss 或 yyyyMMdd
	StartTime string `json:"start_time"`
}
