/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// NearRealtimeCostGetV30ResponseDataListInner struct for NearRealtimeCostGetV30ResponseDataListInner
type NearRealtimeCostGetV30ResponseDataListInner struct {
	// 广告主id
	AccountId *int64 `json:"account_id,omitempty"`
	// 消耗，单位(元)
	Cost *float64 `json:"cost,omitempty"`
	// 日期，
	Date *string `json:"date,omitempty"`
	// 共享钱包id
	SharedWalletId *int64 `json:"shared_wallet_id,omitempty"`
}
