/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response struct for CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response
type CgTransferV2BpCanTransferBalanceBetweenAccountGetV30Response struct {
	//
	Code *int64                                                            `json:"code,omitempty"`
	Data *CgTransferV2BpCanTransferBalanceBetweenAccountGetV30ResponseData `json:"data,omitempty"`
	//
	Message *string `json:"message,omitempty"`
	//
	RequestId *string `json:"request_id,omitempty"`
}
