/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferDetailGetV30DataTransferStatus 转账状态
type CgTransferV2WalletTransferDetailGetV30DataTransferStatus string

// List of cg_transfer_v2_wallet_transfer_detail_get_v3.0_data_transfer_status
const (
	NO_TRANSFER_CgTransferV2WalletTransferDetailGetV30DataTransferStatus      CgTransferV2WalletTransferDetailGetV30DataTransferStatus = "NO_TRANSFER"
	TRANSFER_FAILED_CgTransferV2WalletTransferDetailGetV30DataTransferStatus  CgTransferV2WalletTransferDetailGetV30DataTransferStatus = "TRANSFER_FAILED"
	TRANSFER_ING_CgTransferV2WalletTransferDetailGetV30DataTransferStatus     CgTransferV2WalletTransferDetailGetV30DataTransferStatus = "TRANSFER_ING"
	TRANSFER_PART_CgTransferV2WalletTransferDetailGetV30DataTransferStatus    CgTransferV2WalletTransferDetailGetV30DataTransferStatus = "TRANSFER_PART"
	TRANSFER_SUCCESS_CgTransferV2WalletTransferDetailGetV30DataTransferStatus CgTransferV2WalletTransferDetailGetV30DataTransferStatus = "TRANSFER_SUCCESS"
)

// Ptr returns reference to cg_transfer_v2_wallet_transfer_detail_get_v3.0_data_transfer_status value
func (v CgTransferV2WalletTransferDetailGetV30DataTransferStatus) Ptr() *CgTransferV2WalletTransferDetailGetV30DataTransferStatus {
	return &v
}
