/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletTransferCreateV30Origin 转账来源
type CgTransferV2WalletTransferCreateV30Origin string

// List of cg_transfer_v2_wallet_transfer_create_v3.0_origin
const (
	AGENT_WALLET_MAPI_CgTransferV2WalletTransferCreateV30Origin CgTransferV2WalletTransferCreateV30Origin = "AGENT_WALLET_MAPI"
	BP_WALLET_MAPI_CgTransferV2WalletTransferCreateV30Origin    CgTransferV2WalletTransferCreateV30Origin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_wallet_transfer_create_v3.0_origin value
func (v CgTransferV2WalletTransferCreateV30Origin) Ptr() *CgTransferV2WalletTransferCreateV30Origin {
	return &v
}
