/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2BpTransferCreateV30Origin 转账来源
type CgTransferV2BpTransferCreateV30Origin string

// List of cg_transfer_v2_bp_transfer_create_v3.0_origin
const (
	BP_ACCOUNT_WALLET_MAPI_CgTransferV2BpTransferCreateV30Origin CgTransferV2BpTransferCreateV30Origin = "BP_ACCOUNT_WALLET_MAPI"
	BP_MAPI_CgTransferV2BpTransferCreateV30Origin                CgTransferV2BpTransferCreateV30Origin = "BP_MAPI"
)

// Ptr returns reference to cg_transfer_v2_bp_transfer_create_v3.0_origin value
func (v CgTransferV2BpTransferCreateV30Origin) Ptr() *CgTransferV2BpTransferCreateV30Origin {
	return &v
}
