/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin
type CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin string

// List of cg_transfer_v2_wallet_can_transfer_balance_between_account_get_v3.0_origin
const (
	BP_WALLET_MAPI_CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v2_wallet_can_transfer_balance_between_account_get_v3.0_origin value
func (v CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin) Ptr() *CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30Origin {
	return &v
}
