/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30ResponseData
type EbpGroupBindAccountDeleteV30ResponseData struct {
	//
	FailedAccounts []*EbpGroupBindAccountDeleteV30ResponseDataFailedAccountsInner `json:"failed_accounts,omitempty"`
	// 默认同步执行，超出30个账户数量，异步执行
	IsAsync *bool `json:"is_async,omitempty"`
	// 异步执行时的任务ID
	TaskId *int64 `json:"task_id,omitempty"`
}
