/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpSubGroupCreateV30Request struct for EbpSubGroupCreateV30Request
type EbpSubGroupCreateV30Request struct {
	// 父节点组织ID
	EnterpriseOrganizationId int64 `json:"enterprise_organization_id"`
	// 资产所属账户
	Name string `json:"name"`
}
