/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30AccountsAccountType 账户的业务线
type EbpGroupBindAccountDeleteV30AccountsAccountType string

// List of ebp_group_bind_account_delete_v3.0_accounts_account_type
const (
	AD_EbpGroupBindAccountDeleteV30AccountsAccountType        EbpGroupBindAccountDeleteV30AccountsAccountType = "AD"
	DOU_PLUS_EbpGroupBindAccountDeleteV30AccountsAccountType  EbpGroupBindAccountDeleteV30AccountsAccountType = "DOU_PLUS"
	LOCAL_EbpGroupBindAccountDeleteV30AccountsAccountType     EbpGroupBindAccountDeleteV30AccountsAccountType = "LOCAL"
	QIANCHUAN_EbpGroupBindAccountDeleteV30AccountsAccountType EbpGroupBindAccountDeleteV30AccountsAccountType = "QIANCHUAN"
	STAR_EbpGroupBindAccountDeleteV30AccountsAccountType      EbpGroupBindAccountDeleteV30AccountsAccountType = "STAR"
)

// Ptr returns reference to ebp_group_bind_account_delete_v3.0_accounts_account_type value
func (v EbpGroupBindAccountDeleteV30AccountsAccountType) Ptr() *EbpGroupBindAccountDeleteV30AccountsAccountType {
	return &v
}
