/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// PromotionEcosystemRiskFailedReasonGetV30ResponseData
type PromotionEcosystemRiskFailedReasonGetV30ResponseData struct {
	//
	MaterialReject []*PromotionEcosystemRiskFailedReasonGetV30ResponseDataMaterialRejectInner `json:"material_reject,omitempty"`
	//
	PromotionId *int64 `json:"promotion_id,omitempty"`
}
