/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30RequestAccountsInnerGroupQueriesInner struct for EbpGroupBindAccountUpdateV30RequestAccountsInnerGroupQueriesInner
type EbpGroupBindAccountUpdateV30RequestAccountsInnerGroupQueriesInner struct {
	// 全选的组织ID
	GroupId   int64                                                     `json:"group_id"`
	QueryType EbpGroupBindAccountUpdateV30AccountsGroupQueriesQueryType `json:"query_type"`
}
