/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QualAccountListV2ResponseDataUserAccountInfosInner struct for QualAccountListV2ResponseDataUserAccountInfosInner
type QualAccountListV2ResponseDataUserAccountInfosInner struct {
	// 账户 id
	AccountId int64 `json:"account_id"`
	// 服务商公司的名称
	AgentCompanyName *string `json:"agent_company_name,omitempty"`
	// 邮箱
	Email *string `json:"email,omitempty"`
	// 昵称
	Nickname *string `json:"nickname,omitempty"`
	// owner 的 uid
	OwnerUid *int64 `json:"owner_uid,omitempty"`
	// 手机号
	Phone *string `json:"phone,omitempty"`
}
