/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// QianchuanOverallStarProductGetV10ResponseDataProductListInfosInner struct for QianchuanOverallStarProductGetV10ResponseDataProductListInfosInner
type QianchuanOverallStarProductGetV10ResponseDataProductListInfosInner struct {
	ProductInfo *QianchuanOverallStarProductGetV10ResponseDataProductListInfosInnerProductInfo `json:"product_info,omitempty"`
}
