/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType 选择组织ID下账户范围，只直连账户/包含下级节点的账户。
type EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType string

// List of ebp_group_bind_account_delete_v3.0_accounts_group_queries_query_type
const (
	DIRECT_EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType   EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType = "DIRECT"
	TRAVERSE_EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType = "TRAVERSE"
)

// Ptr returns reference to ebp_group_bind_account_delete_v3.0_accounts_group_queries_query_type value
func (v EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType) Ptr() *EbpGroupBindAccountDeleteV30AccountsGroupQueriesQueryType {
	return &v
}
