/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// ToolsProjectDiagnosisSuggestionListV30ResponseData
type ToolsProjectDiagnosisSuggestionListV30ResponseData struct {
	// 项目诊断建议列表
	Results []*ToolsProjectDiagnosisSuggestionListV30ResponseDataResultsInner `json:"results,omitempty"`
}
