/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType
type OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType string

// List of oc_project_ecosystem_risk_failed_reason_get_v3.0_data_material_reject_type
const (
	ANCHOR_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType                 OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "ANCHOR"
	AWEME_NICK_NAME_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType        OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "AWEME_NICK_NAME"
	CALL_TO_ACTION_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType         OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CALL_TO_ACTION"
	CREATIVE_CAROUSEL_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType      OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_CAROUSEL"
	CREATIVE_COMPONENT_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType     OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_COMPONENT"
	CREATIVE_IMAGE_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType         OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_IMAGE"
	CREATIVE_TITLE_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType         OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_TITLE"
	CREATIVE_URL_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType           OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_URL"
	CREATIVE_VIDEO_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType         OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "CREATIVE_VIDEO"
	OPEN_URL_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType               OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "OPEN_URL"
	PRODUCT_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType                OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT"
	PRODUCT_DESCRIBE_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType       OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_DESCRIBE"
	PRODUCT_IMAGE_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType          OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_IMAGE"
	PRODUCT_SELLING_POINTS_OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType = "PRODUCT_SELLING_POINTS"
)

// Ptr returns reference to oc_project_ecosystem_risk_failed_reason_get_v3.0_data_material_reject_type value
func (v OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType) Ptr() *OcProjectEcosystemRiskFailedReasonGetV30DataMaterialRejectType {
	return &v
}
