/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType
type CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType string

// List of cg_transfer_v3_wallet_can_transfer_balance_between_account_get_v3.0_user_type
const (
	AGENT_CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType = "AGENT"
	BP_CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType    CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType = "BP"
)

// Ptr returns reference to cg_transfer_v3_wallet_can_transfer_balance_between_account_get_v3.0_user_type value
func (v CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType) Ptr() *CgTransferV3WalletCanTransferBalanceBetweenAccountGetV30UserType {
	return &v
}
