/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StdProjectUpdateV30AudienceCarrier
type StdProjectUpdateV30AudienceCarrier string

// List of std_project_update_v3.0_audience_carrier
const (
	MOBILE_StdProjectUpdateV30AudienceCarrier StdProjectUpdateV30AudienceCarrier = "MOBILE"
	TELCOM_StdProjectUpdateV30AudienceCarrier StdProjectUpdateV30AudienceCarrier = "TELCOM"
	UNICOM_StdProjectUpdateV30AudienceCarrier StdProjectUpdateV30AudienceCarrier = "UNICOM"
)

// Ptr returns reference to std_project_update_v3.0_audience_carrier value
func (v StdProjectUpdateV30AudienceCarrier) Ptr() *StdProjectUpdateV30AudienceCarrier {
	return &v
}
