/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferDetailGetV30DataOrigin 转账来源
type CgTransferV3WalletTransferDetailGetV30DataOrigin string

// List of cg_transfer_v3_wallet_transfer_detail_get_v3.0_data_origin
const (
	AGENT_MAPI_CgTransferV3WalletTransferDetailGetV30DataOrigin             CgTransferV3WalletTransferDetailGetV30DataOrigin = "AGENT_MAPI"
	AGENT_WALLET_MAPI_CgTransferV3WalletTransferDetailGetV30DataOrigin      CgTransferV3WalletTransferDetailGetV30DataOrigin = "AGENT_WALLET_MAPI"
	BP_ACCOUNT_WALLET_MAPI_CgTransferV3WalletTransferDetailGetV30DataOrigin CgTransferV3WalletTransferDetailGetV30DataOrigin = "BP_ACCOUNT_WALLET_MAPI"
	BP_MAPI_CgTransferV3WalletTransferDetailGetV30DataOrigin                CgTransferV3WalletTransferDetailGetV30DataOrigin = "BP_MAPI"
	BP_WALLET_MAPI_CgTransferV3WalletTransferDetailGetV30DataOrigin         CgTransferV3WalletTransferDetailGetV30DataOrigin = "BP_WALLET_MAPI"
)

// Ptr returns reference to cg_transfer_v3_wallet_transfer_detail_get_v3.0_data_origin value
func (v CgTransferV3WalletTransferDetailGetV30DataOrigin) Ptr() *CgTransferV3WalletTransferDetailGetV30DataOrigin {
	return &v
}
