/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountCreateV30AccountsAccountType 账户的业务线
type EbpGroupBindAccountCreateV30AccountsAccountType string

// List of ebp_group_bind_account_create_v3.0_accounts_account_type
const (
	AD_EbpGroupBindAccountCreateV30AccountsAccountType        EbpGroupBindAccountCreateV30AccountsAccountType = "AD"
	DOU_PLUS_EbpGroupBindAccountCreateV30AccountsAccountType  EbpGroupBindAccountCreateV30AccountsAccountType = "DOU_PLUS"
	LOCAL_EbpGroupBindAccountCreateV30AccountsAccountType     EbpGroupBindAccountCreateV30AccountsAccountType = "LOCAL"
	QIANCHUAN_EbpGroupBindAccountCreateV30AccountsAccountType EbpGroupBindAccountCreateV30AccountsAccountType = "QIANCHUAN"
	STAR_EbpGroupBindAccountCreateV30AccountsAccountType      EbpGroupBindAccountCreateV30AccountsAccountType = "STAR"
)

// Ptr returns reference to ebp_group_bind_account_create_v3.0_accounts_account_type value
func (v EbpGroupBindAccountCreateV30AccountsAccountType) Ptr() *EbpGroupBindAccountCreateV30AccountsAccountType {
	return &v
}
