/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfo 备款钱包独有信息
type SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfo struct {
	// 客户自身钱包所属的公司id
	CompanyId *int64 `json:"company_id,omitempty"`
	// 代理给客户授权的ebp_id、或者客户自身钱包所属的ebp_id
	EbpId           *int64                                                                                  `json:"ebp_id,omitempty"`
	MainSharedRange *SharedWalletWalletInfoGetV30ResponseDataWalletInfoInnerManageWalletInfoMainSharedRange `json:"main_shared_range,omitempty"`
	// 所属大钱包ID
	MainWalletId *int64 `json:"main_wallet_id,omitempty"`
}
