/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpAdvBindGroupGetV30ResponseDataGroupInfosInner struct for EbpAdvBindGroupGetV30ResponseDataGroupInfosInner
type EbpAdvBindGroupGetV30ResponseDataGroupInfosInner struct {
	//
	GrooupName *string `json:"grooup_name,omitempty"`
	//
	GroupId *int64 `json:"group_id,omitempty"`
}
