/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// UbaToolAdCreateCreateV10Request struct for UbaToolAdCreateCreateV10Request
type UbaToolAdCreateCreateV10Request struct {
	// 广告主ID
	AdvertiserId int64 `json:"advertiser_id"`
	// 项目id
	CdpProjectId int64 `json:"cdp_project_id"`
	// 创建类型
	CreateType int64 `json:"create_type"`
	// 预览模式，只返回预估结果不实际执行
	DryRun *bool `json:"dry_run,omitempty"`
	// 指定新建素材lego_mid, 不保证一定新建
	LegoMidList []int64 `json:"lego_mid_list,omitempty"`
	// 操作原因
	Reason *string `json:"reason,omitempty"`
}
