/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemTaskProviderInfo
type StarMcnProviderGetTaskItemListV2ResponseDataItemsInnerItemTaskProviderInfo struct {
	//
	ProviderAdShareRatio *int64 `json:"provider_ad_share_ratio,omitempty"`
}
