/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerPayee 加款方
type CgTransferV3WalletTransferCreateV30RequestTransferParticipantListInnerPayee struct {
	// 加款方账户id
	AccountId int64 `json:"account_id"`
}
