/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountUpdateV30ResponseDataFailedAccountsInner struct for EbpGroupBindAccountUpdateV30ResponseDataFailedAccountsInner
type EbpGroupBindAccountUpdateV30ResponseDataFailedAccountsInner struct {
	//
	AccountId int64 `json:"account_id"`
	//
	ErrCode int64 `json:"err_code"`
	//
	ErrMsg string `json:"err_msg"`
}
