/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayer 减款方
type CgTransferV2WalletCanTransferBalanceBetweenAccountGetV30TransferParticipantListInnerPayer struct {
	// 减款方账户id
	AccountId int64 `json:"account_id"`
}
