/*
Oceanengine Open Api

巨量引擎开放平台 Open Api


*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// EbpGroupBindAccountDeleteV30ResponseDataFailedAccountsInner struct for EbpGroupBindAccountDeleteV30ResponseDataFailedAccountsInner
type EbpGroupBindAccountDeleteV30ResponseDataFailedAccountsInner struct {
	//
	AccountId int64 `json:"account_id"`
	//
	ErrCode int64 `json:"err_code"`
	//
	ErrMsg string `json:"err_msg"`
}
